// flow-typed signature: a3c6ba6ca8bdd875081282b7039cf47f
// flow-typed version: <<STUB>>/jest-mock_v24.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-mock/build-es5/index' {
  declare module.exports: any;
}

declare module 'jest-mock/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-mock/build-es5/index.js' {
  declare module.exports: $Exports<'jest-mock/build-es5/index'>;
}
declare module 'jest-mock/build/index.js' {
  declare module.exports: $Exports<'jest-mock/build/index'>;
}
