// flow-typed signature: 4996af5695c1d82b2b06dd8b263ba2de
// flow-typed version: <<STUB>>/@uber/typed-rpc-cli_v^1.7.3/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/typed-rpc-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/typed-rpc-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@uber/typed-rpc-cli/bin/cli' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/config.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/convert-case.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/multiple-web-rpc-target.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/multiple.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/populous.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/replace-extension.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/staging.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/add-comment' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/babel-opts' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/babel-plugin-transform-tree-shake' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/convert-case' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/ensure-import-declaration' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/file-utils' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-graphql-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-plugin-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-plugin-register-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-register-graphql-links' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-register-graphql-plugins' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-resolvers' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-rpc-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-schemas' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-type-imports' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-named-exports' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-services' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-thrift-files' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-unique-token-plugin-pair' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/index' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/link' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/load-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/main' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/mod-flow' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/parse-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/remove-unused-imports' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/replace-extension' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/test-utils/run-test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/update-flow' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/update-main-schema' {
  declare module.exports: any;
}

// Filename aliases
declare module '@uber/typed-rpc-cli/bin/cli.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/bin/cli'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/config.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/config.test'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/convert-case.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/convert-case.test'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/multiple-web-rpc-target.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/multiple-web-rpc-target.test'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/multiple.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/multiple.test'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/populous.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/populous.test'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/replace-extension.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/replace-extension.test'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/staging.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/staging.test'>;
}
declare module '@uber/typed-rpc-cli/src/add-comment.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/add-comment'>;
}
declare module '@uber/typed-rpc-cli/src/babel-opts.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/babel-opts'>;
}
declare module '@uber/typed-rpc-cli/src/babel-plugin-transform-tree-shake.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/babel-plugin-transform-tree-shake'>;
}
declare module '@uber/typed-rpc-cli/src/convert-case.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/convert-case'>;
}
declare module '@uber/typed-rpc-cli/src/ensure-import-declaration.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/ensure-import-declaration'>;
}
declare module '@uber/typed-rpc-cli/src/file-utils.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/file-utils'>;
}
declare module '@uber/typed-rpc-cli/src/generate-graphql-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-graphql-code'>;
}
declare module '@uber/typed-rpc-cli/src/generate-plugin-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-plugin-code'>;
}
declare module '@uber/typed-rpc-cli/src/generate-plugin-register-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-plugin-register-code'>;
}
declare module '@uber/typed-rpc-cli/src/generate-register-graphql-links.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-register-graphql-links'>;
}
declare module '@uber/typed-rpc-cli/src/generate-register-graphql-plugins.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-register-graphql-plugins'>;
}
declare module '@uber/typed-rpc-cli/src/generate-resolvers.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-resolvers'>;
}
declare module '@uber/typed-rpc-cli/src/generate-rpc-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-rpc-code'>;
}
declare module '@uber/typed-rpc-cli/src/generate-schemas.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-schemas'>;
}
declare module '@uber/typed-rpc-cli/src/generate-type-imports.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-type-imports'>;
}
declare module '@uber/typed-rpc-cli/src/generate.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate'>;
}
declare module '@uber/typed-rpc-cli/src/get-named-exports.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-named-exports'>;
}
declare module '@uber/typed-rpc-cli/src/get-services.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-services'>;
}
declare module '@uber/typed-rpc-cli/src/get-thrift-files.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-thrift-files'>;
}
declare module '@uber/typed-rpc-cli/src/get-unique-token-plugin-pair.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-unique-token-plugin-pair'>;
}
declare module '@uber/typed-rpc-cli/src/index.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/index'>;
}
declare module '@uber/typed-rpc-cli/src/link.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/link'>;
}
declare module '@uber/typed-rpc-cli/src/load-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/load-config'>;
}
declare module '@uber/typed-rpc-cli/src/main.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/main'>;
}
declare module '@uber/typed-rpc-cli/src/mod-flow.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/mod-flow'>;
}
declare module '@uber/typed-rpc-cli/src/parse-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/parse-config'>;
}
declare module '@uber/typed-rpc-cli/src/remove-unused-imports.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/remove-unused-imports'>;
}
declare module '@uber/typed-rpc-cli/src/replace-extension.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/replace-extension'>;
}
declare module '@uber/typed-rpc-cli/src/test-utils/run-test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/test-utils/run-test'>;
}
declare module '@uber/typed-rpc-cli/src/update-flow.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/update-flow'>;
}
declare module '@uber/typed-rpc-cli/src/update-main-schema.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/update-main-schema'>;
}
