# ═════ Packages to publish ═════

["@uber/create-uber-web"]
# prior : "5.1.1"
version = "5.1.2"

["@uber/fusion-plugin-logtron"]
# prior : "3.0.0"
version = "3.0.1"

["@uber/fusion-plugin-logtron-react"]
# prior : "3.0.0"
version = "3.0.1"

[jazelle]
# prior : "0.0.0-alpha.10"
version = "0.0.0-alpha.11"

# ═════ Unchanged packages ═════

["@uber/fusion-analyticsjs-utils"]
publish = false
version = "2.1.1"

["@uber/fusion-dev-cli"]
publish = false
version = "3.1.1"

["@uber/fusion-legacy-styling-compat-mixin"]
publish = false
version = "2.1.1"

["@uber/fusion-metrics"]
publish = false
version = "1.1.1"

["@uber/fusion-migrate"]
publish = false
version = "1.3.1"

["@uber/fusion-plugin-analytics-session"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-atreyu"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-auth-headers"]
publish = false
version = "3.2.0"

["@uber/fusion-plugin-bedrock-compat"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-error-handling"]
publish = false
version = "2.2.0"

["@uber/fusion-plugin-events-adapter"]
publish = false
version = "3.1.1"

["@uber/fusion-plugin-feature-toggles"]
publish = false
version = "3.1.1"

["@uber/fusion-plugin-feature-toggles-react"]
publish = false
version = "3.1.1"

["@uber/fusion-plugin-flipr"]
publish = false
version = "2.2.0"

["@uber/fusion-plugin-galileo"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-google-analytics"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-google-analytics-react"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-graphql-logging-middleware"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-graphql-metrics"]
publish = false
version = "1.2.1"

["@uber/fusion-plugin-heatpipe"]
publish = false
version = "3.1.1"

["@uber/fusion-plugin-initial-state-compat"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-logger"]
publish = false
version = "0.2.0"

["@uber/fusion-plugin-m3"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-m3-react"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-magellan"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-marketing"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-page-skeleton-compat"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-proxy-compat"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-rosetta"]
publish = false
version = "2.4.1"

["@uber/fusion-plugin-s3-asset-proxying"]
publish = false
version = "2.2.1"

["@uber/fusion-plugin-secrets"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-secure-headers"]
publish = false
version = "5.1.1"

["@uber/fusion-plugin-tchannel"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-tealium"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-tealium-react"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-tracer"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-uber-xhr-compat"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-universal-logger-compat"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-universal-m3-compat"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-web-rpc-compat"]
publish = false
version = "1.1.1"

[create-fusion-app]
publish = false
version = "1.1.1"

[create-fusion-plugin]
publish = false
version = "1.1.1"

[eslint-config-fusion]
publish = false
version = "6.2.0"

[fusion-cli]
publish = false
version = "2.8.0"

[fusion-core]
publish = false
version = "2.2.0"

[fusion-plugin-apollo]
publish = false
version = "3.4.1"

[fusion-plugin-browser-performance-emitter]
publish = false
version = "2.2.1"

[fusion-plugin-connected-react-router]
publish = false
version = "2.1.1"

[fusion-plugin-csrf-protection]
publish = false
version = "3.1.1"

[fusion-plugin-error-handling]
publish = false
version = "2.2.1"

[fusion-plugin-font-loader-react]
publish = false
version = "2.1.1"

[fusion-plugin-http-handler]
publish = false
version = "1.1.1"

[fusion-plugin-i18n]
publish = false
version = "2.4.1"

[fusion-plugin-i18n-react]
publish = false
version = "3.1.1"

[fusion-plugin-introspect]
publish = false
version = "1.1.1"

[fusion-plugin-jwt]
publish = false
version = "2.1.1"

[fusion-plugin-node-performance-emitter]
publish = false
version = "2.1.1"

[fusion-plugin-react-helmet-async]
publish = false
version = "2.2.1"

[fusion-plugin-react-redux]
publish = false
version = "2.1.1"

[fusion-plugin-react-router]
publish = false
version = "2.2.1"

[fusion-plugin-redux-action-emitter-enhancer]
publish = false
version = "3.1.1"

[fusion-plugin-rpc]
publish = false
version = "3.5.0"

[fusion-plugin-rpc-redux-react]
publish = false
version = "4.3.0"

[fusion-plugin-service-worker]
publish = false
version = "3.1.1"

[fusion-plugin-styletron-react]
publish = false
version = "3.1.1"

[fusion-plugin-universal-events]
publish = false
version = "2.1.1"

[fusion-plugin-universal-events-react]
publish = false
version = "2.2.1"

[fusion-plugin-universal-logger]
publish = false
version = "2.1.1"

[fusion-plugin-web-app-manifest]
publish = false
version = "1.1.1"

[fusion-react]
publish = false
version = "4.0.0"

[fusion-rpc-redux]
publish = false
version = "2.2.0"

[fusion-scaffolder]
publish = false
version = "1.1.1"

[fusion-test-utils]
publish = false
version = "2.1.1"

[fusion-tokens]
publish = false
version = "2.1.1"


