// flow-typed signature: 72b16e1fbf1702fefe093af7d481102d
// flow-typed version: <<STUB>>/fusion-cli_v1.13.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fusion-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fusion-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fusion-cli/bin/cli-runner' {
  declare module.exports: any;
}

declare module 'fusion-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-asseturl/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-asseturl/test/index.test' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-chunkid/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-chunkid/test/index.test' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-gql/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-gql/test/index.test' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-i18n/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-pure-create-plugin/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-pure-create-plugin/test/index.test' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-ids/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-ids/test/index.test' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-paths/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-paths/test/index.test' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-transform-tree-shake/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-transform-tree-shake/test/index.test' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-utils/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-utils/replace-import-declaration' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-utils/test/index.test' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/babel-plugins/babel-plugin-utils/visit-named-module' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/compiler' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/convert-coverage' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/dev-runtime' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/get-babel-config' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/get-webpack-config' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/base-jest-config' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/cli-options' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/jest-config' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/jest-framework-setup-15' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/jest-framework-setup-16' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/jest-framework-shims' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/jest-transformer' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/jsdom/jest.config' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/node/jest.config' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/jest/results-processor' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/load-fusionrc' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/babel-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/chunk-ids-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/chunk-manifest-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/chunk-url-map-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/file-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/gql-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/i18n-manifest-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/json-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/loader-context' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/sync-chunk-ids-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/loaders/sync-chunk-paths-loader' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/merge-chunk-metadata' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/persistent-disk-cache' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/plugins/child-compilation-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/plugins/chunk-id-prefix-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/plugins/client-chunk-metadata-state-hydrator-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/plugins/i18n-discovery-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/plugins/instrumented-import-dependency-template-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/plugins/loader-context-provider-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/server-error' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/shared-state-containers' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/spawn' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/test-runtime' {
  declare module.exports: any;
}

declare module 'fusion-cli/build/types' {
  declare module.exports: any;
}

declare module 'fusion-cli/commands/build' {
  declare module.exports: any;
}

declare module 'fusion-cli/commands/dev' {
  declare module.exports: any;
}

declare module 'fusion-cli/commands/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/commands/profile' {
  declare module.exports: any;
}

declare module 'fusion-cli/commands/start' {
  declare module.exports: any;
}

declare module 'fusion-cli/commands/test-app' {
  declare module.exports: any;
}

declare module 'fusion-cli/commands/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/entries/client-entry' {
  declare module.exports: any;
}

declare module 'fusion-cli/entries/client-public-path' {
  declare module.exports: any;
}

declare module 'fusion-cli/entries/server-entry' {
  declare module.exports: any;
}

declare module 'fusion-cli/entries/server-public-path' {
  declare module.exports: any;
}

declare module 'fusion-cli/flow-typed/globals' {
  declare module.exports: any;
}

declare module 'fusion-cli/flow-typed/npm/jest_v23.x.x' {
  declare module.exports: any;
}

declare module 'fusion-cli/flow-typed/npm/winston_v3.x.x' {
  declare module.exports: any;
}

declare module 'fusion-cli/flow-typed/tape-cup_v4.x.x' {
  declare module.exports: any;
}

declare module 'fusion-cli/get-compilation-metadata' {
  declare module.exports: any;
}

declare module 'fusion-cli/get-test-files' {
  declare module.exports: any;
}

declare module 'fusion-cli/jest.config' {
  declare module.exports: any;
}

declare module 'fusion-cli/lib/compression/brotli-webpack-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/lib/compression/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/lib/compression/svgo-webpack-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/lib/compression/zopfli-webpack-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/lib/simple-webpack-dev-middleware/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/lib/simple-webpack-dev-middleware/lib/Shared' {
  declare module.exports: any;
}

declare module 'fusion-cli/lib/strip-prefix' {
  declare module.exports: any;
}

declare module 'fusion-cli/lib/strip-prefix.spec' {
  declare module.exports: any;
}

declare module 'fusion-cli/plugins/assets-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/plugins/context-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/plugins/critical-chunk-ids-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/plugins/server-error-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/plugins/ssr-plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/plugins/types' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/assets-client-fetch/fixture/src/home' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/assets-client-fetch/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/assets/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/assets/fixture/src/server-asset' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/assets/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/colocated-tests-error/fixture/src/foo/__tests__/foo-test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/colocated-tests-error/fixture/src/foo/foo' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/colocated-tests-error/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/colocated-tests-error/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/compress-assets/fixture/src/assets/file_to_compress' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/compress-assets/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/compress-assets/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/constants' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/custom-babel/fixture/node_modules/mapbox-gl/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/custom-babel/fixture/node_modules/other/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/custom-babel/fixture/plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/custom-babel/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/custom-babel/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/custom-body-template/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/custom-body-template/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/dynamic' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/root' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/routes' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/split-route-content' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/split-route' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import-app/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import/fixture/src/dynamic' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import/fixture/src/dynamic2' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/dynamic-import/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/empty/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/empty/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/errors' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/fusionrc/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/fusionrc/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/gql/fixture/node_modules/fusion-apollo/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/gql/fixture/node_modules/graphql-tag/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/gql/fixture/src/__tests__/schema' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/gql/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/gql/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/hmr-simple-app/fixture/src/home' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/hmr-simple-app/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/hmr-simple-app/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/hmr-with-router/fixture/src/home' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/hmr-with-router/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/hmr-with-router/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/hmr' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/json-static-assets/fixture/src/home' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/json-static-assets/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/json-static-assets/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/missing-entry-file/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/missing-module/fixture/src/__tests__/index.browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/missing-module/fixture/src/__tests__/index.node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/missing-module/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/missing-module/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/named-async-main/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/named-async-main/fixture/src/plugins/health' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/named-async-main/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/noop-test/fixture/src/__tests__/index.browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/noop-test/fixture/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/noop-test/fixture/src/__tests__/index.node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/noop-test/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/noop-test/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/noop/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/noop/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/prefix/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/prefix/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/redirect/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/redirect/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-assets/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-assets/fixture/src/server-assets' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-assets/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-render-error/fixture/src/home' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-render-error/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-render-error/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-startup-control/fixture/delayed-compilation' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-startup-control/fixture/src/home' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-startup-control/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-startup-control/fixture/src/root' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-startup-control/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-startup-error/fixture/src/home' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-startup-error/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/server-startup-error/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/setup' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split-translations/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split-translations/fixture/src/root' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split-translations/fixture/src/routes' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split-translations/fixture/src/split1' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split-translations/fixture/src/split2' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split-translations/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split/fixture/src/test-a' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split/fixture/src/test-b' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split/fixture/src/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/split/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/syntax-error/fixture/src/__tests__/index.browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/syntax-error/fixture/src/__tests__/index.node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/syntax-error/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/syntax-error/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/should-not-count-for-coverage' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__foo__/passes' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__integration__/mytest.node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/class-props' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/dynamic-imports' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/environment-variables' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/fail-browser.browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/fail-node.node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/fails' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/pass-browser.browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/pass-node.node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/passes' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/snapshot-enzyme-no-match' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/snapshot-no-match' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/class-props' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/count-tests' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/dynamic-import' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/foo' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/istanbul-ignore-coverage-cli' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/istanbul-ignore-coverage' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/not-imported-in-tests' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/snapshot' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-app/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-babel/fixture/src/__tests__/babel' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-babel/fixture/src/plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/test-jest-babel/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/transpile-all-files/fixture/common/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/transpile-all-files/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/transpile-async-plugin/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/transpile-async-plugin/fixture/src/plugin' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/transpile-async-plugin/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/transpile-node-modules/fixture/node_modules/fixture-es2017-pkg/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/transpile-node-modules/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/transpile-node-modules/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/node_modules/fixture-pkg/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/node_modules/fixture-pkg/unused' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/node_modules/fixture-pkg/used' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/unused2' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/used2' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/user-code' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking-unused/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/default-export-browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/default-export-node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/instrumented-as-pure-browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/instrumented-as-pure-node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/named-export-browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/named-export-node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/tree-shaking/test' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/__tests__/index.browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/__tests__/index.node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/__tests__/index.browser' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/__tests__/index.node' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/main' {
  declare module.exports: any;
}

declare module 'fusion-cli/test/e2e/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fusion-cli/bin/cli-runner.js' {
  declare module.exports: $Exports<'fusion-cli/bin/cli-runner'>;
}
declare module 'fusion-cli/bin/cli.js' {
  declare module.exports: $Exports<'fusion-cli/bin/cli'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-asseturl/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-asseturl/index'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-asseturl/test/index.test.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-asseturl/test/index.test'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-chunkid/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-chunkid/index'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-chunkid/test/index.test.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-chunkid/test/index.test'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-gql/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-gql/index'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-gql/test/index.test.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-gql/test/index.test'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-i18n/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-i18n/index'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-pure-create-plugin/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-pure-create-plugin/index'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-pure-create-plugin/test/index.test.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-pure-create-plugin/test/index.test'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-ids/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-ids/index'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-ids/test/index.test.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-ids/test/index.test'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-paths/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-paths/index'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-paths/test/index.test.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-sync-chunk-paths/test/index.test'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-transform-tree-shake/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-transform-tree-shake/index'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-transform-tree-shake/test/index.test.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-transform-tree-shake/test/index.test'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-utils/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-utils/index'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-utils/replace-import-declaration.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-utils/replace-import-declaration'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-utils/test/index.test.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-utils/test/index.test'>;
}
declare module 'fusion-cli/build/babel-plugins/babel-plugin-utils/visit-named-module.js' {
  declare module.exports: $Exports<'fusion-cli/build/babel-plugins/babel-plugin-utils/visit-named-module'>;
}
declare module 'fusion-cli/build/compiler.js' {
  declare module.exports: $Exports<'fusion-cli/build/compiler'>;
}
declare module 'fusion-cli/build/convert-coverage.js' {
  declare module.exports: $Exports<'fusion-cli/build/convert-coverage'>;
}
declare module 'fusion-cli/build/dev-runtime.js' {
  declare module.exports: $Exports<'fusion-cli/build/dev-runtime'>;
}
declare module 'fusion-cli/build/get-babel-config.js' {
  declare module.exports: $Exports<'fusion-cli/build/get-babel-config'>;
}
declare module 'fusion-cli/build/get-webpack-config.js' {
  declare module.exports: $Exports<'fusion-cli/build/get-webpack-config'>;
}
declare module 'fusion-cli/build/jest/base-jest-config.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/base-jest-config'>;
}
declare module 'fusion-cli/build/jest/cli-options.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/cli-options'>;
}
declare module 'fusion-cli/build/jest/jest-config.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/jest-config'>;
}
declare module 'fusion-cli/build/jest/jest-framework-setup-15.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/jest-framework-setup-15'>;
}
declare module 'fusion-cli/build/jest/jest-framework-setup-16.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/jest-framework-setup-16'>;
}
declare module 'fusion-cli/build/jest/jest-framework-shims.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/jest-framework-shims'>;
}
declare module 'fusion-cli/build/jest/jest-transformer.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/jest-transformer'>;
}
declare module 'fusion-cli/build/jest/jsdom/jest.config.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/jsdom/jest.config'>;
}
declare module 'fusion-cli/build/jest/node/jest.config.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/node/jest.config'>;
}
declare module 'fusion-cli/build/jest/results-processor.js' {
  declare module.exports: $Exports<'fusion-cli/build/jest/results-processor'>;
}
declare module 'fusion-cli/build/load-fusionrc.js' {
  declare module.exports: $Exports<'fusion-cli/build/load-fusionrc'>;
}
declare module 'fusion-cli/build/loaders/babel-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/babel-loader'>;
}
declare module 'fusion-cli/build/loaders/chunk-ids-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/chunk-ids-loader'>;
}
declare module 'fusion-cli/build/loaders/chunk-manifest-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/chunk-manifest-loader'>;
}
declare module 'fusion-cli/build/loaders/chunk-url-map-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/chunk-url-map-loader'>;
}
declare module 'fusion-cli/build/loaders/file-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/file-loader'>;
}
declare module 'fusion-cli/build/loaders/gql-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/gql-loader'>;
}
declare module 'fusion-cli/build/loaders/i18n-manifest-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/i18n-manifest-loader'>;
}
declare module 'fusion-cli/build/loaders/index.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/index'>;
}
declare module 'fusion-cli/build/loaders/json-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/json-loader'>;
}
declare module 'fusion-cli/build/loaders/loader-context.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/loader-context'>;
}
declare module 'fusion-cli/build/loaders/sync-chunk-ids-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/sync-chunk-ids-loader'>;
}
declare module 'fusion-cli/build/loaders/sync-chunk-paths-loader.js' {
  declare module.exports: $Exports<'fusion-cli/build/loaders/sync-chunk-paths-loader'>;
}
declare module 'fusion-cli/build/merge-chunk-metadata.js' {
  declare module.exports: $Exports<'fusion-cli/build/merge-chunk-metadata'>;
}
declare module 'fusion-cli/build/persistent-disk-cache.js' {
  declare module.exports: $Exports<'fusion-cli/build/persistent-disk-cache'>;
}
declare module 'fusion-cli/build/plugins/child-compilation-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/build/plugins/child-compilation-plugin'>;
}
declare module 'fusion-cli/build/plugins/chunk-id-prefix-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/build/plugins/chunk-id-prefix-plugin'>;
}
declare module 'fusion-cli/build/plugins/client-chunk-metadata-state-hydrator-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/build/plugins/client-chunk-metadata-state-hydrator-plugin'>;
}
declare module 'fusion-cli/build/plugins/i18n-discovery-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/build/plugins/i18n-discovery-plugin'>;
}
declare module 'fusion-cli/build/plugins/instrumented-import-dependency-template-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/build/plugins/instrumented-import-dependency-template-plugin'>;
}
declare module 'fusion-cli/build/plugins/loader-context-provider-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/build/plugins/loader-context-provider-plugin'>;
}
declare module 'fusion-cli/build/server-error.js' {
  declare module.exports: $Exports<'fusion-cli/build/server-error'>;
}
declare module 'fusion-cli/build/shared-state-containers.js' {
  declare module.exports: $Exports<'fusion-cli/build/shared-state-containers'>;
}
declare module 'fusion-cli/build/spawn.js' {
  declare module.exports: $Exports<'fusion-cli/build/spawn'>;
}
declare module 'fusion-cli/build/test-runtime.js' {
  declare module.exports: $Exports<'fusion-cli/build/test-runtime'>;
}
declare module 'fusion-cli/build/types.js' {
  declare module.exports: $Exports<'fusion-cli/build/types'>;
}
declare module 'fusion-cli/commands/build.js' {
  declare module.exports: $Exports<'fusion-cli/commands/build'>;
}
declare module 'fusion-cli/commands/dev.js' {
  declare module.exports: $Exports<'fusion-cli/commands/dev'>;
}
declare module 'fusion-cli/commands/index.js' {
  declare module.exports: $Exports<'fusion-cli/commands/index'>;
}
declare module 'fusion-cli/commands/profile.js' {
  declare module.exports: $Exports<'fusion-cli/commands/profile'>;
}
declare module 'fusion-cli/commands/start.js' {
  declare module.exports: $Exports<'fusion-cli/commands/start'>;
}
declare module 'fusion-cli/commands/test-app.js' {
  declare module.exports: $Exports<'fusion-cli/commands/test-app'>;
}
declare module 'fusion-cli/commands/test.js' {
  declare module.exports: $Exports<'fusion-cli/commands/test'>;
}
declare module 'fusion-cli/entries/client-entry.js' {
  declare module.exports: $Exports<'fusion-cli/entries/client-entry'>;
}
declare module 'fusion-cli/entries/client-public-path.js' {
  declare module.exports: $Exports<'fusion-cli/entries/client-public-path'>;
}
declare module 'fusion-cli/entries/server-entry.js' {
  declare module.exports: $Exports<'fusion-cli/entries/server-entry'>;
}
declare module 'fusion-cli/entries/server-public-path.js' {
  declare module.exports: $Exports<'fusion-cli/entries/server-public-path'>;
}
declare module 'fusion-cli/flow-typed/globals.js' {
  declare module.exports: $Exports<'fusion-cli/flow-typed/globals'>;
}
declare module 'fusion-cli/flow-typed/npm/jest_v23.x.x.js' {
  declare module.exports: $Exports<'fusion-cli/flow-typed/npm/jest_v23.x.x'>;
}
declare module 'fusion-cli/flow-typed/npm/winston_v3.x.x.js' {
  declare module.exports: $Exports<'fusion-cli/flow-typed/npm/winston_v3.x.x'>;
}
declare module 'fusion-cli/flow-typed/tape-cup_v4.x.x.js' {
  declare module.exports: $Exports<'fusion-cli/flow-typed/tape-cup_v4.x.x'>;
}
declare module 'fusion-cli/get-compilation-metadata.js' {
  declare module.exports: $Exports<'fusion-cli/get-compilation-metadata'>;
}
declare module 'fusion-cli/get-test-files.js' {
  declare module.exports: $Exports<'fusion-cli/get-test-files'>;
}
declare module 'fusion-cli/jest.config.js' {
  declare module.exports: $Exports<'fusion-cli/jest.config'>;
}
declare module 'fusion-cli/lib/compression/brotli-webpack-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/lib/compression/brotli-webpack-plugin'>;
}
declare module 'fusion-cli/lib/compression/index.js' {
  declare module.exports: $Exports<'fusion-cli/lib/compression/index'>;
}
declare module 'fusion-cli/lib/compression/svgo-webpack-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/lib/compression/svgo-webpack-plugin'>;
}
declare module 'fusion-cli/lib/compression/zopfli-webpack-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/lib/compression/zopfli-webpack-plugin'>;
}
declare module 'fusion-cli/lib/simple-webpack-dev-middleware/index.js' {
  declare module.exports: $Exports<'fusion-cli/lib/simple-webpack-dev-middleware/index'>;
}
declare module 'fusion-cli/lib/simple-webpack-dev-middleware/lib/Shared.js' {
  declare module.exports: $Exports<'fusion-cli/lib/simple-webpack-dev-middleware/lib/Shared'>;
}
declare module 'fusion-cli/lib/strip-prefix.js' {
  declare module.exports: $Exports<'fusion-cli/lib/strip-prefix'>;
}
declare module 'fusion-cli/lib/strip-prefix.spec.js' {
  declare module.exports: $Exports<'fusion-cli/lib/strip-prefix.spec'>;
}
declare module 'fusion-cli/plugins/assets-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/plugins/assets-plugin'>;
}
declare module 'fusion-cli/plugins/context-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/plugins/context-plugin'>;
}
declare module 'fusion-cli/plugins/critical-chunk-ids-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/plugins/critical-chunk-ids-plugin'>;
}
declare module 'fusion-cli/plugins/server-error-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/plugins/server-error-plugin'>;
}
declare module 'fusion-cli/plugins/ssr-plugin.js' {
  declare module.exports: $Exports<'fusion-cli/plugins/ssr-plugin'>;
}
declare module 'fusion-cli/plugins/types.js' {
  declare module.exports: $Exports<'fusion-cli/plugins/types'>;
}
declare module 'fusion-cli/test/e2e/assets-client-fetch/fixture/src/home.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/assets-client-fetch/fixture/src/home'>;
}
declare module 'fusion-cli/test/e2e/assets-client-fetch/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/assets-client-fetch/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/assets/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/assets/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/assets/fixture/src/server-asset.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/assets/fixture/src/server-asset'>;
}
declare module 'fusion-cli/test/e2e/assets/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/assets/test'>;
}
declare module 'fusion-cli/test/e2e/colocated-tests-error/fixture/src/foo/__tests__/foo-test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/colocated-tests-error/fixture/src/foo/__tests__/foo-test'>;
}
declare module 'fusion-cli/test/e2e/colocated-tests-error/fixture/src/foo/foo.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/colocated-tests-error/fixture/src/foo/foo'>;
}
declare module 'fusion-cli/test/e2e/colocated-tests-error/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/colocated-tests-error/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/colocated-tests-error/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/colocated-tests-error/test'>;
}
declare module 'fusion-cli/test/e2e/compress-assets/fixture/src/assets/file_to_compress.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/compress-assets/fixture/src/assets/file_to_compress'>;
}
declare module 'fusion-cli/test/e2e/compress-assets/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/compress-assets/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/compress-assets/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/compress-assets/test'>;
}
declare module 'fusion-cli/test/e2e/constants.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/constants'>;
}
declare module 'fusion-cli/test/e2e/custom-babel/fixture/node_modules/mapbox-gl/index.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/custom-babel/fixture/node_modules/mapbox-gl/index'>;
}
declare module 'fusion-cli/test/e2e/custom-babel/fixture/node_modules/other/index.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/custom-babel/fixture/node_modules/other/index'>;
}
declare module 'fusion-cli/test/e2e/custom-babel/fixture/plugin.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/custom-babel/fixture/plugin'>;
}
declare module 'fusion-cli/test/e2e/custom-babel/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/custom-babel/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/custom-babel/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/custom-babel/test'>;
}
declare module 'fusion-cli/test/e2e/custom-body-template/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/custom-body-template/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/custom-body-template/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/custom-body-template/test'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/dynamic.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import-app/fixture/src/dynamic'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import-app/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/root.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import-app/fixture/src/root'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/routes.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import-app/fixture/src/routes'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/split-route-content.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import-app/fixture/src/split-route-content'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import-app/fixture/src/split-route.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import-app/fixture/src/split-route'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import-app/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import-app/test'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import/fixture/src/dynamic.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import/fixture/src/dynamic'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import/fixture/src/dynamic2.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import/fixture/src/dynamic2'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/dynamic-import/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/dynamic-import/test'>;
}
declare module 'fusion-cli/test/e2e/empty/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/empty/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/empty/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/empty/test'>;
}
declare module 'fusion-cli/test/e2e/errors.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/errors'>;
}
declare module 'fusion-cli/test/e2e/fusionrc/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/fusionrc/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/fusionrc/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/fusionrc/test'>;
}
declare module 'fusion-cli/test/e2e/gql/fixture/node_modules/fusion-apollo/index.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/gql/fixture/node_modules/fusion-apollo/index'>;
}
declare module 'fusion-cli/test/e2e/gql/fixture/node_modules/graphql-tag/index.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/gql/fixture/node_modules/graphql-tag/index'>;
}
declare module 'fusion-cli/test/e2e/gql/fixture/src/__tests__/schema.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/gql/fixture/src/__tests__/schema'>;
}
declare module 'fusion-cli/test/e2e/gql/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/gql/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/gql/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/gql/test'>;
}
declare module 'fusion-cli/test/e2e/hmr-simple-app/fixture/src/home.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/hmr-simple-app/fixture/src/home'>;
}
declare module 'fusion-cli/test/e2e/hmr-simple-app/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/hmr-simple-app/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/hmr-simple-app/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/hmr-simple-app/test'>;
}
declare module 'fusion-cli/test/e2e/hmr-with-router/fixture/src/home.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/hmr-with-router/fixture/src/home'>;
}
declare module 'fusion-cli/test/e2e/hmr-with-router/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/hmr-with-router/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/hmr-with-router/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/hmr-with-router/test'>;
}
declare module 'fusion-cli/test/e2e/hmr.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/hmr'>;
}
declare module 'fusion-cli/test/e2e/json-static-assets/fixture/src/home.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/json-static-assets/fixture/src/home'>;
}
declare module 'fusion-cli/test/e2e/json-static-assets/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/json-static-assets/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/json-static-assets/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/json-static-assets/test'>;
}
declare module 'fusion-cli/test/e2e/missing-entry-file/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/missing-entry-file/test'>;
}
declare module 'fusion-cli/test/e2e/missing-module/fixture/src/__tests__/index.browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/missing-module/fixture/src/__tests__/index.browser'>;
}
declare module 'fusion-cli/test/e2e/missing-module/fixture/src/__tests__/index.node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/missing-module/fixture/src/__tests__/index.node'>;
}
declare module 'fusion-cli/test/e2e/missing-module/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/missing-module/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/missing-module/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/missing-module/test'>;
}
declare module 'fusion-cli/test/e2e/named-async-main/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/named-async-main/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/named-async-main/fixture/src/plugins/health.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/named-async-main/fixture/src/plugins/health'>;
}
declare module 'fusion-cli/test/e2e/named-async-main/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/named-async-main/test'>;
}
declare module 'fusion-cli/test/e2e/noop-test/fixture/src/__tests__/index.browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/noop-test/fixture/src/__tests__/index.browser'>;
}
declare module 'fusion-cli/test/e2e/noop-test/fixture/src/__tests__/index.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/noop-test/fixture/src/__tests__/index'>;
}
declare module 'fusion-cli/test/e2e/noop-test/fixture/src/__tests__/index.node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/noop-test/fixture/src/__tests__/index.node'>;
}
declare module 'fusion-cli/test/e2e/noop-test/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/noop-test/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/noop-test/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/noop-test/test'>;
}
declare module 'fusion-cli/test/e2e/noop/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/noop/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/noop/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/noop/test'>;
}
declare module 'fusion-cli/test/e2e/prefix/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/prefix/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/prefix/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/prefix/test'>;
}
declare module 'fusion-cli/test/e2e/redirect/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/redirect/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/redirect/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/redirect/test'>;
}
declare module 'fusion-cli/test/e2e/server-assets/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-assets/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/server-assets/fixture/src/server-assets.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-assets/fixture/src/server-assets'>;
}
declare module 'fusion-cli/test/e2e/server-assets/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-assets/test'>;
}
declare module 'fusion-cli/test/e2e/server-render-error/fixture/src/home.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-render-error/fixture/src/home'>;
}
declare module 'fusion-cli/test/e2e/server-render-error/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-render-error/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/server-render-error/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-render-error/test'>;
}
declare module 'fusion-cli/test/e2e/server-startup-control/fixture/delayed-compilation.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-startup-control/fixture/delayed-compilation'>;
}
declare module 'fusion-cli/test/e2e/server-startup-control/fixture/src/home.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-startup-control/fixture/src/home'>;
}
declare module 'fusion-cli/test/e2e/server-startup-control/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-startup-control/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/server-startup-control/fixture/src/root.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-startup-control/fixture/src/root'>;
}
declare module 'fusion-cli/test/e2e/server-startup-control/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-startup-control/test'>;
}
declare module 'fusion-cli/test/e2e/server-startup-error/fixture/src/home.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-startup-error/fixture/src/home'>;
}
declare module 'fusion-cli/test/e2e/server-startup-error/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-startup-error/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/server-startup-error/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/server-startup-error/test'>;
}
declare module 'fusion-cli/test/e2e/setup.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/setup'>;
}
declare module 'fusion-cli/test/e2e/split-translations/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split-translations/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/split-translations/fixture/src/root.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split-translations/fixture/src/root'>;
}
declare module 'fusion-cli/test/e2e/split-translations/fixture/src/routes.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split-translations/fixture/src/routes'>;
}
declare module 'fusion-cli/test/e2e/split-translations/fixture/src/split1.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split-translations/fixture/src/split1'>;
}
declare module 'fusion-cli/test/e2e/split-translations/fixture/src/split2.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split-translations/fixture/src/split2'>;
}
declare module 'fusion-cli/test/e2e/split-translations/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split-translations/test'>;
}
declare module 'fusion-cli/test/e2e/split/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/split/fixture/src/test-a.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split/fixture/src/test-a'>;
}
declare module 'fusion-cli/test/e2e/split/fixture/src/test-b.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split/fixture/src/test-b'>;
}
declare module 'fusion-cli/test/e2e/split/fixture/src/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split/fixture/src/test'>;
}
declare module 'fusion-cli/test/e2e/split/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/split/test'>;
}
declare module 'fusion-cli/test/e2e/syntax-error/fixture/src/__tests__/index.browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/syntax-error/fixture/src/__tests__/index.browser'>;
}
declare module 'fusion-cli/test/e2e/syntax-error/fixture/src/__tests__/index.node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/syntax-error/fixture/src/__tests__/index.node'>;
}
declare module 'fusion-cli/test/e2e/syntax-error/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/syntax-error/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/syntax-error/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/syntax-error/test'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/should-not-count-for-coverage.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/should-not-count-for-coverage'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__foo__/passes.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__foo__/passes'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__integration__/mytest.node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__integration__/mytest.node'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/class-props.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/class-props'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/dynamic-imports.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/dynamic-imports'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/environment-variables.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/environment-variables'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/fail-browser.browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/fail-browser.browser'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/fail-node.node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/fail-node.node'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/fails.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/fails'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/pass-browser.browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/pass-browser.browser'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/pass-node.node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/pass-node.node'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/passes.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/passes'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/snapshot-enzyme-no-match.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/snapshot-enzyme-no-match'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/snapshot-no-match.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/__tests__/snapshot-no-match'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/class-props.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/class-props'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/count-tests.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/count-tests'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/dynamic-import.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/dynamic-import'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/foo.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/foo'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/istanbul-ignore-coverage-cli.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/istanbul-ignore-coverage-cli'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/istanbul-ignore-coverage.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/istanbul-ignore-coverage'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/not-imported-in-tests.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/not-imported-in-tests'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/fixture/src/snapshot.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/fixture/src/snapshot'>;
}
declare module 'fusion-cli/test/e2e/test-jest-app/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-app/test'>;
}
declare module 'fusion-cli/test/e2e/test-jest-babel/fixture/src/__tests__/babel.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-babel/fixture/src/__tests__/babel'>;
}
declare module 'fusion-cli/test/e2e/test-jest-babel/fixture/src/plugin.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-babel/fixture/src/plugin'>;
}
declare module 'fusion-cli/test/e2e/test-jest-babel/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/test-jest-babel/test'>;
}
declare module 'fusion-cli/test/e2e/transpile-all-files/fixture/common/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/transpile-all-files/fixture/common/test'>;
}
declare module 'fusion-cli/test/e2e/transpile-all-files/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/transpile-all-files/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/transpile-async-plugin/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/transpile-async-plugin/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/transpile-async-plugin/fixture/src/plugin.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/transpile-async-plugin/fixture/src/plugin'>;
}
declare module 'fusion-cli/test/e2e/transpile-async-plugin/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/transpile-async-plugin/test'>;
}
declare module 'fusion-cli/test/e2e/transpile-node-modules/fixture/node_modules/fixture-es2017-pkg/index.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/transpile-node-modules/fixture/node_modules/fixture-es2017-pkg/index'>;
}
declare module 'fusion-cli/test/e2e/transpile-node-modules/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/transpile-node-modules/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/transpile-node-modules/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/transpile-node-modules/test'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/node_modules/fixture-pkg/index.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking-unused/fixture/node_modules/fixture-pkg/index'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/node_modules/fixture-pkg/unused.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking-unused/fixture/node_modules/fixture-pkg/unused'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/node_modules/fixture-pkg/used.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking-unused/fixture/node_modules/fixture-pkg/used'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/unused2.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/unused2'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/used2.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/used2'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/user-code.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking-unused/fixture/src/user-code'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking-unused/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking-unused/test'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/default-export-browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/default-export-browser'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/default-export-node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/default-export-node'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/instrumented-as-pure-browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/instrumented-as-pure-browser'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/instrumented-as-pure-node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/instrumented-as-pure-node'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/named-export-browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/named-export-browser'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/named-export-node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking/fixture/src/plugins/named-export-node'>;
}
declare module 'fusion-cli/test/e2e/tree-shaking/test.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/tree-shaking/test'>;
}
declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/__tests__/index.browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/__tests__/index.browser'>;
}
declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/__tests__/index.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/__tests__/index'>;
}
declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/__tests__/index.node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/__tests__/index.node'>;
}
declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/unhandled-promise-rejection-browser/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/__tests__/index.browser.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/__tests__/index.browser'>;
}
declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/__tests__/index.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/__tests__/index'>;
}
declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/__tests__/index.node.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/__tests__/index.node'>;
}
declare module 'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/main.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/unhandled-promise-rejection-server/fixture/src/main'>;
}
declare module 'fusion-cli/test/e2e/utils.js' {
  declare module.exports: $Exports<'fusion-cli/test/e2e/utils'>;
}
