// flow-typed signature: 9c4aff5efe80a202b500d02245762db2
// flow-typed version: <<STUB>>/jest-environment-jsdom_v^23.4.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-jsdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-environment-jsdom/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-environment-jsdom/build/index.js' {
  declare module.exports: $Exports<'jest-environment-jsdom/build/index'>;
}
