// flow-typed signature: 2ee66abb6999cef502d4f34157a1ffae
// flow-typed version: <<STUB>>/sade_v^1.4.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sade/lib/index' {
  declare module.exports: any;
}

declare module 'sade/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sade/lib/index.js' {
  declare module.exports: $Exports<'sade/lib/index'>;
}
declare module 'sade/lib/utils.js' {
  declare module.exports: $Exports<'sade/lib/utils'>;
}
