// flow-typed signature: 4bcbc8fe2f7c4a1fb2e7431f67b16634
// flow-typed version: <<STUB>>/eslint-plugin-graphql_v^3.0.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-graphql/lib/constants' {
  declare module.exports: any;
}

declare module 'eslint-plugin-graphql/lib/createRule' {
  declare module.exports: any;
}

declare module 'eslint-plugin-graphql/lib/customGraphQLValidationRules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-graphql/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-graphql/lib/constants.js' {
  declare module.exports: $Exports<'eslint-plugin-graphql/lib/constants'>;
}
declare module 'eslint-plugin-graphql/lib/createRule.js' {
  declare module.exports: $Exports<'eslint-plugin-graphql/lib/createRule'>;
}
declare module 'eslint-plugin-graphql/lib/customGraphQLValidationRules.js' {
  declare module.exports: $Exports<'eslint-plugin-graphql/lib/customGraphQLValidationRules'>;
}
declare module 'eslint-plugin-graphql/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-graphql/lib/index'>;
}
