// flow-typed signature: b804f69c79a872fde582e7c780b2addf
// flow-typed version: <<STUB>>/long_v^4.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'long'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'long' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'long/dist/long' {
  declare module.exports: any;
}

declare module 'long/src/long' {
  declare module.exports: any;
}

// Filename aliases
declare module 'long/dist/long.js' {
  declare module.exports: $Exports<'long/dist/long'>;
}
declare module 'long/index' {
  declare module.exports: $Exports<'long'>;
}
declare module 'long/index.js' {
  declare module.exports: $Exports<'long'>;
}
declare module 'long/src/long.js' {
  declare module.exports: $Exports<'long/src/long'>;
}
