// flow-typed signature: f4be2868b9709aa955cfca4d43b05c73
// flow-typed version: <<STUB>>/@apollo/react-hoc_v^3.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@apollo/react-hoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@apollo/react-hoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@apollo/react-hoc/lib/graphql' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/hoc-utils' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/index' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/mutation-hoc' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/query-hoc' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/react-hoc.cjs' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/react-hoc.cjs.min' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/react-hoc.esm' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/react-hoc.umd' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/subscription-hoc' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/types' {
  declare module.exports: any;
}

declare module '@apollo/react-hoc/lib/withApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module '@apollo/react-hoc/lib/graphql.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/graphql'>;
}
declare module '@apollo/react-hoc/lib/hoc-utils.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/hoc-utils'>;
}
declare module '@apollo/react-hoc/lib/index.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/index'>;
}
declare module '@apollo/react-hoc/lib/mutation-hoc.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/mutation-hoc'>;
}
declare module '@apollo/react-hoc/lib/query-hoc.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/query-hoc'>;
}
declare module '@apollo/react-hoc/lib/react-hoc.cjs.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/react-hoc.cjs'>;
}
declare module '@apollo/react-hoc/lib/react-hoc.cjs.min.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/react-hoc.cjs.min'>;
}
declare module '@apollo/react-hoc/lib/react-hoc.esm.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/react-hoc.esm'>;
}
declare module '@apollo/react-hoc/lib/react-hoc.umd.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/react-hoc.umd'>;
}
declare module '@apollo/react-hoc/lib/subscription-hoc.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/subscription-hoc'>;
}
declare module '@apollo/react-hoc/lib/types.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/types'>;
}
declare module '@apollo/react-hoc/lib/withApollo.js' {
  declare module.exports: $Exports<'@apollo/react-hoc/lib/withApollo'>;
}
