npmScopes:
  uber:
    npmAlwaysAuth: true
    npmRegistryServer: "https://unpm.uberinternal.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-sources.cjs

packageExtensions:
  "@apollo/react-ssr@*":
    peerDependencies:
      apollo-client: "*"
  "eslint-config-uber-universal-stage-3@*":
    peerDependencies:
      babel-eslint: "*"
  "baseui@*":
    dependencies:
      styletron-standard: "*"
  "@uber/icons@*":
    peerDependencies:
      react: "*"
  "jest-jasmine2@*":
    peerDependencies:
      prettier: "*"
  "jest-config@*":
    peerDependencies:
      prettier: "*"
  "jest-runner@*":
    peerDependencies:
      prettier: "*"
  "@jest/core@*":
    peerDependencies:
      prettier: "*"
  "@jest/test-sequencer@*":
    peerDependencies:
      prettier: "*"
  "jest-cli@*":
    peerDependencies:
      prettier: "*"
  "jest-runtime@*":
    peerDependencies:
      prettier: "*"
  "jest@*":
    peerDependencies:
      prettier: "*"
