// flow-typed signature: 780b41404a373c25f2374efbef04a942
// flow-typed version: <<STUB>>/@uber/atreyu_v^6.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/atreyu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/atreyu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@uber/atreyu/examples/atreyu' {
  declare module.exports: any;
}

declare module '@uber/atreyu/examples/graph' {
  declare module.exports: any;
}

declare module '@uber/atreyu/examples/http-tchannel-thrift/http-tchannel-thrift' {
  declare module.exports: any;
}

declare module '@uber/atreyu/examples/http-tchannel-thrift/thrift/gen-nodejs/riders_types' {
  declare module.exports: any;
}

declare module '@uber/atreyu/examples/http-tchannel-thrift/thrift/gen-nodejs/Riders' {
  declare module.exports: any;
}

declare module '@uber/atreyu/examples/populous/populous' {
  declare module.exports: any;
}

declare module '@uber/atreyu/examples/request' {
  declare module.exports: any;
}

declare module '@uber/atreyu/lib/atreyu' {
  declare module.exports: any;
}

declare module '@uber/atreyu/lib/helpers/hyperbahn' {
  declare module.exports: any;
}

declare module '@uber/atreyu/lib/helpers/tchannel' {
  declare module.exports: any;
}

declare module '@uber/atreyu/test/atreyu.tap' {
  declare module.exports: any;
}

declare module '@uber/atreyu/test/hyperbahn.tap' {
  declare module.exports: any;
}

declare module '@uber/atreyu/test/index' {
  declare module.exports: any;
}

declare module '@uber/atreyu/test/tchannel.tap' {
  declare module.exports: any;
}

declare module '@uber/atreyu/test/thrift/gen-nodejs/helloworld_types' {
  declare module.exports: any;
}

declare module '@uber/atreyu/test/thrift/gen-nodejs/HelloWorld' {
  declare module.exports: any;
}

// Filename aliases
declare module '@uber/atreyu/examples/atreyu.js' {
  declare module.exports: $Exports<'@uber/atreyu/examples/atreyu'>;
}
declare module '@uber/atreyu/examples/graph.js' {
  declare module.exports: $Exports<'@uber/atreyu/examples/graph'>;
}
declare module '@uber/atreyu/examples/http-tchannel-thrift/http-tchannel-thrift.js' {
  declare module.exports: $Exports<'@uber/atreyu/examples/http-tchannel-thrift/http-tchannel-thrift'>;
}
declare module '@uber/atreyu/examples/http-tchannel-thrift/thrift/gen-nodejs/riders_types.js' {
  declare module.exports: $Exports<'@uber/atreyu/examples/http-tchannel-thrift/thrift/gen-nodejs/riders_types'>;
}
declare module '@uber/atreyu/examples/http-tchannel-thrift/thrift/gen-nodejs/Riders.js' {
  declare module.exports: $Exports<'@uber/atreyu/examples/http-tchannel-thrift/thrift/gen-nodejs/Riders'>;
}
declare module '@uber/atreyu/examples/populous/populous.js' {
  declare module.exports: $Exports<'@uber/atreyu/examples/populous/populous'>;
}
declare module '@uber/atreyu/examples/request.js' {
  declare module.exports: $Exports<'@uber/atreyu/examples/request'>;
}
declare module '@uber/atreyu/index' {
  declare module.exports: $Exports<'@uber/atreyu'>;
}
declare module '@uber/atreyu/index.js' {
  declare module.exports: $Exports<'@uber/atreyu'>;
}
declare module '@uber/atreyu/lib/atreyu.js' {
  declare module.exports: $Exports<'@uber/atreyu/lib/atreyu'>;
}
declare module '@uber/atreyu/lib/helpers/hyperbahn.js' {
  declare module.exports: $Exports<'@uber/atreyu/lib/helpers/hyperbahn'>;
}
declare module '@uber/atreyu/lib/helpers/tchannel.js' {
  declare module.exports: $Exports<'@uber/atreyu/lib/helpers/tchannel'>;
}
declare module '@uber/atreyu/test/atreyu.tap.js' {
  declare module.exports: $Exports<'@uber/atreyu/test/atreyu.tap'>;
}
declare module '@uber/atreyu/test/hyperbahn.tap.js' {
  declare module.exports: $Exports<'@uber/atreyu/test/hyperbahn.tap'>;
}
declare module '@uber/atreyu/test/index.js' {
  declare module.exports: $Exports<'@uber/atreyu/test/index'>;
}
declare module '@uber/atreyu/test/tchannel.tap.js' {
  declare module.exports: $Exports<'@uber/atreyu/test/tchannel.tap'>;
}
declare module '@uber/atreyu/test/thrift/gen-nodejs/helloworld_types.js' {
  declare module.exports: $Exports<'@uber/atreyu/test/thrift/gen-nodejs/helloworld_types'>;
}
declare module '@uber/atreyu/test/thrift/gen-nodejs/HelloWorld.js' {
  declare module.exports: $Exports<'@uber/atreyu/test/thrift/gen-nodejs/HelloWorld'>;
}
