// flow-typed signature: c3742bb871b6f4aa4f0fc4ccc76cde7e
// flow-typed version: <<STUB>>/@uber/node-heatpipe-publisher_v^3.0.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/node-heatpipe-publisher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/node-heatpipe-publisher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@uber/node-heatpipe-publisher/example' {
  declare module.exports: any;
}

declare module '@uber/node-heatpipe-publisher/lib/heatpipe_publisher' {
  declare module.exports: any;
}

declare module '@uber/node-heatpipe-publisher/test/index' {
  declare module.exports: any;
}

declare module '@uber/node-heatpipe-publisher/test/test_heatpipe_publisher' {
  declare module.exports: any;
}

// Filename aliases
declare module '@uber/node-heatpipe-publisher/example.js' {
  declare module.exports: $Exports<'@uber/node-heatpipe-publisher/example'>;
}
declare module '@uber/node-heatpipe-publisher/index' {
  declare module.exports: $Exports<'@uber/node-heatpipe-publisher'>;
}
declare module '@uber/node-heatpipe-publisher/index.js' {
  declare module.exports: $Exports<'@uber/node-heatpipe-publisher'>;
}
declare module '@uber/node-heatpipe-publisher/lib/heatpipe_publisher.js' {
  declare module.exports: $Exports<'@uber/node-heatpipe-publisher/lib/heatpipe_publisher'>;
}
declare module '@uber/node-heatpipe-publisher/test/index.js' {
  declare module.exports: $Exports<'@uber/node-heatpipe-publisher/test/index'>;
}
declare module '@uber/node-heatpipe-publisher/test/test_heatpipe_publisher.js' {
  declare module.exports: $Exports<'@uber/node-heatpipe-publisher/test/test_heatpipe_publisher'>;
}
