// flow-typed signature: 8002dc9f634f3eeff2121a0ee8470d1f
// flow-typed version: <<STUB>>/@uber/standard-fonts_v^0.1.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/standard-fonts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/standard-fonts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@uber/standard-fonts/bin/copy-to-app' {
  declare module.exports: any;
}

declare module '@uber/standard-fonts/src/config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@uber/standard-fonts/bin/copy-to-app.js' {
  declare module.exports: $Exports<'@uber/standard-fonts/bin/copy-to-app'>;
}
declare module '@uber/standard-fonts/src/config.js' {
  declare module.exports: $Exports<'@uber/standard-fonts/src/config'>;
}
