# ═════ Packages to publish ═════

["@uber/create-uber-web"]
# prior : "5.1.7"
version = "5.2.0"

["@uber/fusion-plugin-atreyu"]
# prior : "2.1.3"
version = "2.1.4"

["@uber/fusion-plugin-bedrock-compat"]
# prior : "2.1.3"
version = "2.1.4"

["@uber/fusion-plugin-error-handling"]
# prior : "2.3.1"
version = "2.3.2"

["@uber/fusion-plugin-events-adapter"]
# prior : "3.3.0"
version = "3.3.1"

["@uber/fusion-plugin-feature-toggles"]
# prior : "3.1.5"
version = "3.1.6"

["@uber/fusion-plugin-feature-toggles-react"]
# prior : "3.1.5"
version = "3.1.6"

["@uber/fusion-plugin-galileo"]
# prior : "2.1.3"
version = "2.1.4"

["@uber/fusion-plugin-graphql-logging-middleware"]
# prior : "1.1.4"
version = "1.1.5"

["@uber/fusion-plugin-graphql-metrics"]
# prior : "1.2.4"
version = "1.2.5"

["@uber/fusion-plugin-heatpipe"]
# prior : "3.1.4"
version = "3.1.5"

["@uber/fusion-plugin-logger"]
# prior : "0.2.2"
version = "0.2.3"

["@uber/fusion-plugin-logtron"]
# prior : "3.1.3"
version = "3.2.0"

["@uber/fusion-plugin-m3"]
# prior : "2.1.3"
version = "2.1.4"

["@uber/fusion-plugin-marketing"]
# prior : "2.2.3"
version = "2.2.4"

["@uber/fusion-plugin-proxy-compat"]
# prior : "1.1.4"
version = "1.1.5"

["@uber/fusion-plugin-tchannel"]
# prior : "2.1.3"
version = "2.1.4"

["@uber/fusion-plugin-universal-m3-compat"]
# prior : "1.1.3"
version = "1.1.4"

["@uber/fusion-plugin-web-rpc-compat"]
# prior : "1.1.3"
version = "1.1.4"

[fusion-cli]
# prior : "2.13.0"
version = "2.14.0"

[fusion-plugin-browser-performance-emitter]
# prior : "2.2.3"
version = "2.2.4"

[fusion-plugin-connected-react-router]
# prior : "2.1.6"
version = "2.1.7"

[fusion-plugin-i18n]
# prior : "2.4.3"
version = "2.4.4"

[fusion-plugin-i18n-react]
# prior : "3.1.4"
version = "3.1.5"

[fusion-plugin-node-performance-emitter]
# prior : "2.1.3"
version = "2.1.4"

[fusion-plugin-react-router]
# prior : "2.2.6"
version = "2.2.7"

[fusion-plugin-redux-action-emitter-enhancer]
# prior : "3.1.3"
version = "3.1.4"

[fusion-plugin-rpc]
# prior : "3.5.2"
version = "3.5.3"

[fusion-plugin-rpc-redux-react]
# prior : "4.3.3"
version = "4.3.4"

[fusion-plugin-service-worker]
# prior : "3.1.6"
version = "3.1.7"

[fusion-plugin-styletron-react]
# prior : "3.1.2"
version = "3.2.0"

[fusion-plugin-universal-events]
# prior : "2.1.3"
version = "2.1.4"

[jazelle]
# prior : "0.0.0-alpha.18"
version = "0.0.0-alpha.19"

# ═════ Unchanged packages ═════

["@uber/fusion-analyticsjs-utils"]
publish = false
version = "2.1.2"

["@uber/fusion-dev-cli"]
publish = false
version = "3.1.3"

["@uber/fusion-legacy-styling-compat-mixin"]
publish = false
version = "2.1.2"

["@uber/fusion-metrics"]
publish = false
version = "1.1.2"

["@uber/fusion-migrate"]
publish = false
version = "1.3.2"

["@uber/fusion-plugin-analytics-session"]
publish = false
version = "2.1.2"

["@uber/fusion-plugin-auth-headers"]
publish = false
version = "4.0.0"

["@uber/fusion-plugin-flipr"]
publish = false
version = "2.2.1"

["@uber/fusion-plugin-google-analytics"]
publish = false
version = "2.1.3"

["@uber/fusion-plugin-initial-state-compat"]
publish = false
version = "1.1.2"

["@uber/fusion-plugin-magellan"]
publish = false
version = "2.1.2"

["@uber/fusion-plugin-page-skeleton-compat"]
publish = false
version = "1.1.2"

["@uber/fusion-plugin-rosetta"]
publish = false
version = "3.0.1"

["@uber/fusion-plugin-s3-asset-proxying"]
publish = false
version = "2.2.2"

["@uber/fusion-plugin-secrets"]
publish = false
version = "2.1.2"

["@uber/fusion-plugin-secure-headers"]
publish = false
version = "5.1.2"

["@uber/fusion-plugin-tealium"]
publish = false
version = "2.1.3"

["@uber/fusion-plugin-tracer"]
publish = false
version = "2.1.2"

["@uber/fusion-plugin-uber-xhr-compat"]
publish = false
version = "1.1.2"

["@uber/fusion-plugin-universal-logger-compat"]
publish = false
version = "1.1.2"

[create-fusion-app]
publish = false
version = "1.1.2"

[create-fusion-plugin]
publish = false
version = "1.1.2"

[eslint-config-fusion]
publish = false
version = "6.2.0"

[fusion-core]
publish = false
version = "2.2.1"

[fusion-plugin-apollo]
publish = false
version = "3.4.4"

[fusion-plugin-csrf-protection]
publish = false
version = "3.1.2"

[fusion-plugin-error-handling]
publish = false
version = "2.2.2"

[fusion-plugin-font-loader-react]
publish = false
version = "2.1.4"

[fusion-plugin-http-handler]
publish = false
version = "1.1.2"

[fusion-plugin-introspect]
publish = false
version = "1.1.2"

[fusion-plugin-jwt]
publish = false
version = "2.1.2"

[fusion-plugin-react-helmet-async]
publish = false
version = "2.2.3"

[fusion-plugin-react-redux]
publish = false
version = "2.1.4"

[fusion-plugin-universal-logger]
publish = false
version = "2.1.2"

[fusion-plugin-web-app-manifest]
publish = false
version = "1.1.2"

[fusion-react]
publish = false
version = "4.0.3"

[fusion-rpc-redux]
publish = false
version = "2.2.1"

[fusion-scaffolder]
publish = false
version = "1.1.2"

[fusion-test-utils]
publish = false
version = "2.1.2"

[fusion-tokens]
publish = false
version = "2.1.2"

