// flow-typed signature: 9ce992f6a618074cecf33feedf858752
// flow-typed version: <<STUB>>/@octokit/rest_v16/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/rest' {
  declare module.exports: any;
}
