// flow-typed signature: f343f4b2e1715d50e23335b255ca5948
// flow-typed version: <<STUB>>/airlock_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'airlock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'airlock' {
  declare module.exports: any;
}
