// flow-typed signature: 3dcca370f6c86f8a998088dc8f3fd4f0
// flow-typed version: <<STUB>>/array-unique_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-unique'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-unique' {
  declare module.exports: any;
}
