// flow-typed signature: 1aa8d3dd97424efb0ee61ce65d9e4e2e
// flow-typed version: <<STUB>>/axios_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios' {
  declare module.exports: any;
}
