// flow-typed signature: 670e9b524e7e215e46dccaa793c14605
// flow-typed version: <<STUB>>/baseui_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'baseui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'baseui' {
  declare module.exports: any;
}
