// flow-typed signature: a3bf1604f889262582f73544c1ccde02
// flow-typed version: <<STUB>>/chrome-remote-interface_v0.27/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrome-remote-interface'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrome-remote-interface' {
  declare module.exports: any;
}
