// flow-typed signature: 7255e7f603026d0fc1196a522529a0e6
// flow-typed version: <<STUB>>/colors_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'colors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'colors' {
  declare module.exports: any;
}
