// flow-typed signature: 0c59ae66a362fa96dd2819b6fb50f2a3
// flow-typed version: <<STUB>>/default-no-import-side-effects-webpack-plugin_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'default-no-import-side-effects-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'default-no-import-side-effects-webpack-plugin' {
  declare module.exports: any;
}
