// flow-typed signature: bc1d3816f1e148b9aa504c5b261b4495
// flow-typed version: <<STUB>>/dottie_v2/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dottie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dottie' {
  declare module.exports: any;
}
