// flow-typed signature: c18ba940db64befbfba412dd1e835b44
// flow-typed version: <<STUB>>/express_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express' {
  declare module.exports: any;
}
