// flow-typed signature: c1951113b75c67a99f1a635b467982c2
// flow-typed version: <<STUB>>/fast-safe-stringify_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-safe-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-safe-stringify' {
  declare module.exports: any;
}
