// flow-typed signature: b654572f5b7bbae50f7a1d983be84a6c
// flow-typed version: <<STUB>>/folder-hash_v3/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'folder-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'folder-hash' {
  declare module.exports: any;
}
