// flow-typed signature: 5d8d6c98e1ecbd48702845e0cd636b54
// flow-typed version: <<STUB>>/form-data_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'form-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'form-data' {
  declare module.exports: any;
}
