// flow-typed signature: cef9d4703348f4b4420e998da42d4511
// flow-typed version: <<STUB>>/formidable_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'formidable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'formidable' {
  declare module.exports: any;
}
