// flow-typed signature: 8ab4fd153b99c024621dd5612004ba25
// flow-typed version: <<STUB>>/gc-stats_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gc-stats'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gc-stats' {
  declare module.exports: any;
}
