// flow-typed signature: d90337a7f2a19898d1ea4fd4a1ab269b
// flow-typed version: <<STUB>>/graphql-middleware_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-middleware' {
  declare module.exports: any;
}
