// flow-typed signature: 592c1b9522b78cfbd7660b28626e47e5
// flow-typed version: <<STUB>>/isbot_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isbot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isbot' {
  declare module.exports: any;
}
