// flow-typed signature: 409d716162d5d225d950b21da4ad29fb
// flow-typed version: <<STUB>>/isobject_v3.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isobject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isobject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'isobject/index' {
  declare module.exports: $Exports<'isobject'>;
}
declare module 'isobject/index.js' {
  declare module.exports: $Exports<'isobject'>;
}
