// flow-typed signature: 9d2f12a37f9b7075d9b009cfe27f217a
// flow-typed version: <<STUB>>/jaeger-client_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jaeger-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jaeger-client' {
  declare module.exports: any;
}
