// flow-typed signature: e10c009062e5a3d8bad9ee9864f5ac1f
// flow-typed version: <<STUB>>/jest-worker_v25.5/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-worker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-worker' {
  declare module.exports: any;
}
