// flow-typed signature: 649b9d1b725a5a69dae982e0f871e25c
// flow-typed version: <<STUB>>/js-yaml_v3/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-yaml' {
  declare module.exports: any;
}
