// flow-typed signature: 46fe06d4f3adc88ab37dc0b07ffa70d0
// flow-typed version: <<STUB>>/jsdom_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdom' {
  declare module.exports: any;
}
