// flow-typed signature: 4c23033004a59f5244c91dab07fe98a2
// flow-typed version: <<STUB>>/json-stringify-safe_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-stringify-safe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-stringify-safe' {
  declare module.exports: any;
}
