// flow-typed signature: a6559ec4edf2ebceaa5a9fbdc3e097e8
// flow-typed version: <<STUB>>/just-kebab-case_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-kebab-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-kebab-case' {
  declare module.exports: any;
}
