// flow-typed signature: 9095d6ff2c171e0bc41456d18e524815
// flow-typed version: <<STUB>>/just-map-object_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-map-object'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-map-object' {
  declare module.exports: any;
}
