// flow-typed signature: a07d39b47565afca80ca00725b6a424a
// flow-typed version: <<STUB>>/just-compare_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-compare' {
  declare module.exports: any;
}
