// flow-typed signature: d2050ea6ac5c6e99b3753e6c4e610f2d
// flow-typed version: <<STUB>>/just-map-values_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-map-values'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-map-values' {
  declare module.exports: any;
}
