// flow-typed signature: aaa25c96c589ff8fb25d1eaa995264ec
// flow-typed version: <<STUB>>/just-extend_v4.2.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-extend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-extend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'just-extend/index' {
  declare module.exports: $Exports<'just-extend'>;
}
declare module 'just-extend/index.js' {
  declare module.exports: $Exports<'just-extend'>;
}
