// flow-typed signature: 22c72a89ff745415c642c4f1b2335d44
// flow-typed version: <<STUB>>/just-snake-case_v1/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-snake-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-snake-case' {
  declare module.exports: any;
}
