// flow-typed signature: 53430f294db48a6c697c39fed2a28c80
// flow-typed version: <<STUB>>/just-compose_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-compose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-compose' {
  declare module.exports: any;
}
