// flow-typed signature: a16a32bbc0dc0394da40c03daf3e32f9
// flow-typed version: <<STUB>>/loader-utils_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loader-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loader-utils' {
  declare module.exports: any;
}
