// flow-typed signature: 8daa92147f0022446606aed76074c03d
// flow-typed version: <<STUB>>/log-update_v3.4/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'log-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'log-update' {
  declare module.exports: any;
}
