// flow-typed signature: af9abe25a81affa23de05531bc8e2283
// flow-typed version: <<STUB>>/lru-cache_v6/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lru-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lru-cache' {
  declare module.exports: any;
}
