// flow-typed signature: 5736da2463e550904bb7b6ca869fe2db
// flow-typed version: <<STUB>>/make-dir_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'make-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'make-dir' {
  declare module.exports: any;
}
