// flow-typed signature: 6c516bc47f19767569023d55c6b74f22
// flow-typed version: <<STUB>>/minimist_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minimist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minimist' {
  declare module.exports: any;
}
