// flow-typed signature: 3333c570c8fd07ced5e621a8b41eb10c
// flow-typed version: <<STUB>>/node-libs-browser_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-libs-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-libs-browser' {
  declare module.exports: any;
}
