// flow-typed signature: 4b4d10a5f460e0b0ba70ae8cd73cadca
// flow-typed version: <<STUB>>/opentracing_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opentracing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opentracing' {
  declare module.exports: any;
}
