// flow-typed signature: f5a7564d6ffa27ff140d932288d7f8a0
// flow-typed version: <<STUB>>/parse-domain_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-domain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-domain' {
  declare module.exports: any;
}
