// flow-typed signature: 3816220aa29f4f716be59aaade94a829
// flow-typed version: <<STUB>>/pnp-webpack-plugin_v1/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pnp-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pnp-webpack-plugin' {
  declare module.exports: any;
}
