// flow-typed signature: ffa26f1417d4612a28d72bc57043eb0e
// flow-typed version: <<STUB>>/progress-bar-webpack-plugin_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'progress-bar-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'progress-bar-webpack-plugin' {
  declare module.exports: any;
}
