// flow-typed signature: e63ffa2fd7cfa4bf281dda3e3ee3c3a0
// flow-typed version: <<STUB>>/puppeteer_v1.x.x/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'puppeteer' {
  declare module.exports: any;
}
