// flow-typed signature: 72575257754391e48e06d8a59b7c52a5
// flow-typed version: <<STUB>>/react-ssr-prepass_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ssr-prepass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ssr-prepass' {
  declare module.exports: any;
}
