// flow-typed signature: b895e5b21884d89d7c8e4f8ae5c01616
// flow-typed version: <<STUB>>/recursive-readdir_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recursive-readdir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recursive-readdir' {
  declare module.exports: any;
}
