// flow-typed signature: 7c957793d48da5e6d5724728f3585f07
// flow-typed version: <<STUB>>/request-ip_v2.1.3/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request-ip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'request-ip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request-ip/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request-ip/dist/index' {
  declare module.exports: $Exports<'request-ip/dist'>;
}
declare module 'request-ip/dist/index.js' {
  declare module.exports: $Exports<'request-ip/dist'>;
}
