// flow-typed signature: c3c69f7c2c6d09046800c01a2bd82684
// flow-typed version: <<STUB>>/sade_v^1.4.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sade/lib' {
  declare module.exports: any;
}

declare module 'sade/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sade/lib/index' {
  declare module.exports: $Exports<'sade/lib'>;
}
declare module 'sade/lib/index.js' {
  declare module.exports: $Exports<'sade/lib'>;
}
declare module 'sade/lib/utils.js' {
  declare module.exports: $Exports<'sade/lib/utils'>;
}
