// flow-typed signature: ae03b9fe96b0bb94b01ef725830b6a4a
// flow-typed version: <<STUB>>/semver_v6/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semver' {
  declare module.exports: any;
}
