// flow-typed signature: 2256f807729e2e25ff6b9279ab6bc433
// flow-typed version: <<STUB>>/sentry-logger_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sentry-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sentry-logger' {
  declare module.exports: any;
}
