// flow-typed signature: 9fbd48f293a5d4f3a40ec46e817cdd87
// flow-typed version: <<STUB>>/simple-git_v1.132/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-git' {
  declare module.exports: any;
}
