// flow-typed signature: c8a3635ca4d80f6f8f735fdefcbd9498
// flow-typed version: <<STUB>>/styletron-engine-atomic_v1.0.8/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-engine-atomic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-engine-atomic' {
  declare module.exports: any;
}
