// flow-typed signature: d5ee28bba7e2c3a4e12005b35cfd5ac4
// flow-typed version: <<STUB>>/styletron-server_v3.0.4/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-server/dist/browser.es2015.es' {
  declare module.exports: any;
}

declare module 'styletron-server/dist/browser.es2017.es' {
  declare module.exports: any;
}

declare module 'styletron-server/dist/browser.es5.es' {
  declare module.exports: any;
}

declare module 'styletron-server/dist/browser.es5' {
  declare module.exports: any;
}

declare module 'styletron-server/dist/index.es' {
  declare module.exports: any;
}

declare module 'styletron-server/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-server/dist/browser.es2015.es.js' {
  declare module.exports: $Exports<'styletron-server/dist/browser.es2015.es'>;
}
declare module 'styletron-server/dist/browser.es2017.es.js' {
  declare module.exports: $Exports<'styletron-server/dist/browser.es2017.es'>;
}
declare module 'styletron-server/dist/browser.es5.es.js' {
  declare module.exports: $Exports<'styletron-server/dist/browser.es5.es'>;
}
declare module 'styletron-server/dist/browser.es5.js' {
  declare module.exports: $Exports<'styletron-server/dist/browser.es5'>;
}
declare module 'styletron-server/dist/index.es.js' {
  declare module.exports: $Exports<'styletron-server/dist/index.es'>;
}
declare module 'styletron-server/dist/index.js' {
  declare module.exports: $Exports<'styletron-server/dist/index'>;
}
