// flow-typed signature: 067ba02fe3fa703291c49152ec0fd481
// flow-typed version: <<STUB>>/styletron-engine-monolithic_v0.0.3/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-engine-monolithic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-engine-monolithic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-engine-monolithic/dist/browser.es2015.es' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/dist/browser.es2017.es' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/dist/browser.es5.es' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/dist/browser.es5' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/dist/index.es' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/dist' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/client/client' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/client/sheet' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/css' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/generate-alphabetic-name' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/hash' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/hyphenate-style-name' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/inject-style-prefixed' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/server/server' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/validate-keyframes-object' {
  declare module.exports: any;
}

declare module 'styletron-engine-monolithic/src/validate-no-mixed-hand' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-engine-monolithic/dist/browser.es2015.es.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/dist/browser.es2015.es'>;
}
declare module 'styletron-engine-monolithic/dist/browser.es2017.es.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/dist/browser.es2017.es'>;
}
declare module 'styletron-engine-monolithic/dist/browser.es5.es.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/dist/browser.es5.es'>;
}
declare module 'styletron-engine-monolithic/dist/browser.es5.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/dist/browser.es5'>;
}
declare module 'styletron-engine-monolithic/dist/index.es.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/dist/index.es'>;
}
declare module 'styletron-engine-monolithic/dist/index' {
  declare module.exports: $Exports<'styletron-engine-monolithic/dist'>;
}
declare module 'styletron-engine-monolithic/dist/index.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/dist'>;
}
declare module 'styletron-engine-monolithic/src/client/client.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/client/client'>;
}
declare module 'styletron-engine-monolithic/src/client/sheet.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/client/sheet'>;
}
declare module 'styletron-engine-monolithic/src/css.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/css'>;
}
declare module 'styletron-engine-monolithic/src/generate-alphabetic-name.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/generate-alphabetic-name'>;
}
declare module 'styletron-engine-monolithic/src/hash.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/hash'>;
}
declare module 'styletron-engine-monolithic/src/hyphenate-style-name.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/hyphenate-style-name'>;
}
declare module 'styletron-engine-monolithic/src/index' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src'>;
}
declare module 'styletron-engine-monolithic/src/index.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src'>;
}
declare module 'styletron-engine-monolithic/src/inject-style-prefixed.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/inject-style-prefixed'>;
}
declare module 'styletron-engine-monolithic/src/server/server.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/server/server'>;
}
declare module 'styletron-engine-monolithic/src/validate-keyframes-object.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/validate-keyframes-object'>;
}
declare module 'styletron-engine-monolithic/src/validate-no-mixed-hand.js' {
  declare module.exports: $Exports<'styletron-engine-monolithic/src/validate-no-mixed-hand'>;
}
