// flow-typed signature: 4a1ccad6a1498ae6218bea7cc941a4b6
// flow-typed version: <<STUB>>/tchannel_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tchannel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tchannel' {
  declare module.exports: any;
}
