// flow-typed signature: b83a478f092942b620088324653c6d3b
// flow-typed version: <<STUB>>/temp_v0.0.33/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'temp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'temp' {
  declare module.exports: any;
}
