// flow-typed signature: f5983fb7854a85a610e0204fa09b932f
// flow-typed version: <<STUB>>/terser-webpack-plugin_v1/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terser-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terser-webpack-plugin' {
  declare module.exports: any;
}
