// flow-typed signature: d6a3b9052345ba39a420fe8047e6d0af
// flow-typed version: <<STUB>>/tmp_v0.0.33/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tmp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tmp' {
  declare module.exports: any;
}
