// flow-typed signature: 86617409b9d6b5553fe61d3110acb0b1
// flow-typed version: <<STUB>>/webpack-sources_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-sources'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-sources' {
  declare module.exports: any;
}
