// flow-typed signature: fe13ee386c3af98bdd0f59c63fff7c3c
// flow-typed version: <<STUB>>/whatwg-fetch_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'whatwg-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'whatwg-fetch' {
  declare module.exports: any;
}
