// flow-typed signature: b3c30005c687ad3814d1738c975afd32
// flow-typed version: <<STUB>>/winston-transport_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-transport' {
  declare module.exports: any;
}
