// flow-typed signature: afc668c0773a9d19aeb4b6fc87d952ca
// flow-typed version: <<STUB>>/ws_vx.x.x/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ws' {
  declare module.exports: any;
}
