// flow-typed signature: 381c717d5c51a763f2592a75068b31bb
// flow-typed version: <<STUB>>/zero-config_v7.1.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zero-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zero-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zero-config/config-wrapper' {
  declare module.exports: any;
}

declare module 'zero-config/errors' {
  declare module.exports: any;
}

declare module 'zero-config/get-config-state' {
  declare module.exports: any;
}

declare module 'zero-config/read-datacenter' {
  declare module.exports: any;
}

declare module 'zero-config/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zero-config/config-wrapper.js' {
  declare module.exports: $Exports<'zero-config/config-wrapper'>;
}
declare module 'zero-config/errors.js' {
  declare module.exports: $Exports<'zero-config/errors'>;
}
declare module 'zero-config/get-config-state.js' {
  declare module.exports: $Exports<'zero-config/get-config-state'>;
}
declare module 'zero-config/index' {
  declare module.exports: $Exports<'zero-config'>;
}
declare module 'zero-config/index.js' {
  declare module.exports: $Exports<'zero-config'>;
}
declare module 'zero-config/read-datacenter.js' {
  declare module.exports: $Exports<'zero-config/read-datacenter'>;
}
declare module 'zero-config/test/index.js' {
  declare module.exports: $Exports<'zero-config/test/index'>;
}
