// flow-typed signature: 9f20a9ac80b10d8f3fa9f8c1164eb46c
// flow-typed version: <<STUB>>/@babel/code-frame_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/code-frame'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/code-frame' {
  declare module.exports: any;
}
