// flow-typed signature: 2e2407d904a34798366a71701f50963e
// flow-typed version: <<STUB>>/@babel/helper-create-regexp-features-plugin_v7.10.4/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/helper-create-regexp-features-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/helper-create-regexp-features-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/helper-create-regexp-features-plugin/lib/features' {
  declare module.exports: any;
}

declare module '@babel/helper-create-regexp-features-plugin/lib' {
  declare module.exports: any;
}

declare module '@babel/helper-create-regexp-features-plugin/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/helper-create-regexp-features-plugin/lib/features.js' {
  declare module.exports: $Exports<'@babel/helper-create-regexp-features-plugin/lib/features'>;
}
declare module '@babel/helper-create-regexp-features-plugin/lib/index' {
  declare module.exports: $Exports<'@babel/helper-create-regexp-features-plugin/lib'>;
}
declare module '@babel/helper-create-regexp-features-plugin/lib/index.js' {
  declare module.exports: $Exports<'@babel/helper-create-regexp-features-plugin/lib'>;
}
declare module '@babel/helper-create-regexp-features-plugin/lib/util.js' {
  declare module.exports: $Exports<'@babel/helper-create-regexp-features-plugin/lib/util'>;
}
