// flow-typed signature: 0702da3e4bd3320a92ee48e216e70f8b
// flow-typed version: <<STUB>>/@babel/parser_v7.10.5/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/parser/bin/babel-parser' {
  declare module.exports: any;
}

declare module '@babel/parser/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/parser/bin/babel-parser.js' {
  declare module.exports: $Exports<'@babel/parser/bin/babel-parser'>;
}
declare module '@babel/parser/lib/index' {
  declare module.exports: $Exports<'@babel/parser/lib'>;
}
declare module '@babel/parser/lib/index.js' {
  declare module.exports: $Exports<'@babel/parser/lib'>;
}
