// flow-typed signature: 75078c20f20a86475456881b88cd55cc
// flow-typed version: <<STUB>>/@babel/plugin-transform-block-scoping_v7.10.5/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-block-scoping'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-block-scoping' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-block-scoping/lib' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-block-scoping/lib/tdz' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-block-scoping/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-block-scoping/lib'>;
}
declare module '@babel/plugin-transform-block-scoping/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-block-scoping/lib'>;
}
declare module '@babel/plugin-transform-block-scoping/lib/tdz.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-block-scoping/lib/tdz'>;
}
