// flow-typed signature: 6424bfaa58d3c1fed1f48e7b96964b4c
// flow-typed version: <<STUB>>/@babel/plugin-transform-modules-commonjs_v7.10.4/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-modules-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-modules-commonjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-modules-commonjs/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-modules-commonjs/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib'>;
}
declare module '@babel/plugin-transform-modules-commonjs/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib'>;
}
