version: '2'
services:
  fusion-rpc-redux:
    build: .
    volumes:
      - .:/fusion-rpc-redux
      - /fusion-rpc-redux/node_modules/
      - /fusion-rpc-redux/dist/
      - /fusion-rpc-redux/dist-tests/
