steps:
  - label: ":docker:"
    timeout_in_minutes: 20
    plugins:
      "docker-compose#v3.0.0":
        build: ci
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
        args:
          - UNPM_TOKEN=$UNPM_TOKEN
    agents:
      queue: private-builders
  - wait
  - label: ":package: :npm:"
    command: node ./private/monorepo-actions/publish.js
    timeout_in_minutes: 20
    plugins:
      "docker-compose#v3.0.0":
        run: ci
        env:
          - UNPM_TOKEN
          - NPM_TOKEN
    agents:
      queue: private-default
