// flow-typed signature: 8081e41b111927b523c7481f8a493fe9
// flow-typed version: <<STUB>>/core-js/stable_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'core-js/stable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'core-js/stable' {
  declare module.exports: any;
}
