# ═════ Packages to publish ═════

["@uber/fusion-plugin-atreyu"]
# prior : "2.1.1"
version = "2.1.2"

["@uber/fusion-plugin-bedrock-compat"]
# prior : "2.1.1"
version = "2.1.2"

["@uber/fusion-plugin-error-handling"]
# prior : "2.2.0"
version = "2.3.0"

["@uber/fusion-plugin-events-adapter"]
# prior : "3.1.1"
version = "3.2.0"

["@uber/fusion-plugin-feature-toggles"]
# prior : "3.1.1"
version = "3.1.2"

["@uber/fusion-plugin-feature-toggles-react"]
# prior : "3.1.1"
version = "3.1.2"

["@uber/fusion-plugin-galileo"]
# prior : "2.1.1"
version = "2.1.2"

["@uber/fusion-plugin-google-analytics"]
# prior : "2.1.1"
version = "2.1.2"

["@uber/fusion-plugin-graphql-logging-middleware"]
# prior : "1.1.1"
version = "1.1.2"

["@uber/fusion-plugin-graphql-metrics"]
# prior : "1.2.1"
version = "1.2.2"

["@uber/fusion-plugin-heatpipe"]
# prior : "3.1.1"
version = "3.1.2"

["@uber/fusion-plugin-logger"]
# prior : "0.2.0"
version = "0.2.1"

["@uber/fusion-plugin-logtron"]
# prior : "3.0.2"
version = "3.1.0"

["@uber/fusion-plugin-m3"]
# prior : "2.1.1"
version = "2.1.2"

["@uber/fusion-plugin-marketing"]
# prior : "2.1.1"
version = "2.2.0"

["@uber/fusion-plugin-proxy-compat"]
# prior : "1.1.1"
version = "1.1.2"

["@uber/fusion-plugin-tchannel"]
# prior : "2.1.1"
version = "2.1.2"

["@uber/fusion-plugin-tealium"]
# prior : "2.1.1"
version = "2.1.2"

["@uber/fusion-plugin-universal-m3-compat"]
# prior : "1.1.1"
version = "1.1.2"

["@uber/fusion-plugin-web-rpc-compat"]
# prior : "1.1.1"
version = "1.1.2"

[fusion-cli]
# prior : "2.8.0"
version = "2.9.0"

[fusion-plugin-apollo]
# prior : "3.4.1"
version = "3.4.2"

[fusion-plugin-connected-react-router]
# prior : "2.1.1"
version = "2.1.2"

[fusion-plugin-font-loader-react]
# prior : "2.1.1"
version = "2.1.2"

[fusion-plugin-i18n]
# prior : "2.4.1"
version = "2.4.2"

[fusion-plugin-i18n-react]
# prior : "3.1.1"
version = "3.1.2"

[fusion-plugin-node-performance-emitter]
# prior : "2.1.1"
version = "2.1.2"

[fusion-plugin-react-redux]
# prior : "2.1.1"
version = "2.1.2"

[fusion-plugin-react-router]
# prior : "2.2.1"
version = "2.2.2"

[fusion-plugin-redux-action-emitter-enhancer]
# prior : "3.1.1"
version = "3.1.2"

[fusion-plugin-rpc]
# prior : "3.5.0"
version = "3.5.1"

[fusion-plugin-rpc-redux-react]
# prior : "4.3.0"
version = "4.3.1"

[fusion-plugin-service-worker]
# prior : "3.1.1"
version = "3.1.2"

[fusion-plugin-universal-events]
# prior : "2.1.1"
version = "2.1.2"

[fusion-react]
# prior : "4.0.0"
version = "4.0.1"

[jazelle]
# prior : "0.0.0-alpha.12"
version = "0.0.0-alpha.13"

# ═════ Unchanged packages ═════

["@uber/create-uber-web"]
publish = false
version = "5.1.3"

["@uber/fusion-analyticsjs-utils"]
publish = false
version = "2.1.1"

["@uber/fusion-dev-cli"]
publish = false
version = "3.1.1"

["@uber/fusion-legacy-styling-compat-mixin"]
publish = false
version = "2.1.1"

["@uber/fusion-metrics"]
publish = false
version = "1.1.1"

["@uber/fusion-migrate"]
publish = false
version = "1.3.1"

["@uber/fusion-plugin-analytics-session"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-auth-headers"]
publish = false
version = "3.2.0"

["@uber/fusion-plugin-flipr"]
publish = false
version = "2.2.0"

["@uber/fusion-plugin-initial-state-compat"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-magellan"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-page-skeleton-compat"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-rosetta"]
publish = false
version = "2.4.1"

["@uber/fusion-plugin-s3-asset-proxying"]
publish = false
version = "2.2.1"

["@uber/fusion-plugin-secrets"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-secure-headers"]
publish = false
version = "5.1.1"

["@uber/fusion-plugin-tracer"]
publish = false
version = "2.1.1"

["@uber/fusion-plugin-uber-xhr-compat"]
publish = false
version = "1.1.1"

["@uber/fusion-plugin-universal-logger-compat"]
publish = false
version = "1.1.1"

[create-fusion-app]
publish = false
version = "1.1.1"

[create-fusion-plugin]
publish = false
version = "1.1.1"

[eslint-config-fusion]
publish = false
version = "6.2.0"

[fusion-core]
publish = false
version = "2.2.0"

[fusion-plugin-browser-performance-emitter]
publish = false
version = "2.2.1"

[fusion-plugin-csrf-protection]
publish = false
version = "3.1.1"

[fusion-plugin-error-handling]
publish = false
version = "2.2.1"

[fusion-plugin-http-handler]
publish = false
version = "1.1.1"

[fusion-plugin-introspect]
publish = false
version = "1.1.1"

[fusion-plugin-jwt]
publish = false
version = "2.1.1"

[fusion-plugin-react-helmet-async]
publish = false
version = "2.2.2"

[fusion-plugin-styletron-react]
publish = false
version = "3.1.1"

[fusion-plugin-universal-logger]
publish = false
version = "2.1.1"

[fusion-plugin-web-app-manifest]
publish = false
version = "1.1.1"

[fusion-rpc-redux]
publish = false
version = "2.2.0"

[fusion-scaffolder]
publish = false
version = "1.1.1"

[fusion-test-utils]
publish = false
version = "2.1.1"

[fusion-tokens]
publish = false
version = "2.1.1"
