// flow-typed signature: 1f308ab20ebe5bafe53b2092eecd8ae5
// flow-typed version: <<STUB>>/@dubstep/core_v2.0.0-2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dubstep/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dubstep/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dubstep/core/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module '@dubstep/core/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module '@dubstep/core/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/core/index' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/core/index.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/create-restore-point' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/create-restore-point.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/ensure-js-imports' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/ensure-js-imports.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/exec' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/exec.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/find-files' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/find-files.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/generate-js' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/generate-js.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/get-restore-point' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/get-restore-point.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/git-clone' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/git-clone.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/git-commit' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/git-commit.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/insert-js-after' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/insert-js-after.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/insert-js-before' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/insert-js-before.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/move-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/move-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/parse-js' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/parse-js.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/read-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/read-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/remove-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/remove-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/remove-js-imports' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/remove-js-imports.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/replace-js' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/replace-js.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/visit-js-import' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/visit-js-import.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-ignore-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-ignore-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-js-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-js-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-js-files' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-js-files.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-json-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-json-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-text-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/with-text-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/write-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/dist/utils/write-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/@babel/parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/@babel/plugin-proposal-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/@babel/plugin-transform-modules-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/@babel/preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/@babel/template_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/@babel/traverse_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/eslint-config-fusion_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/eslint-plugin-cup_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/eslint-plugin-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/execa_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/flow-coverage-report_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/fs-extra_v7.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/globby_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/ini_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/isomorphic-git_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/jest_v23.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/markdown-it_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/npm-watch_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/flow-typed/npm/recast_vx.x.x' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/core/index' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/core/index.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/create-restore-point' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/create-restore-point.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/ensure-js-imports' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/ensure-js-imports.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/exec' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/exec.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/find-files' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/find-files.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/generate-js' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/generate-js.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/get-restore-point' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/get-restore-point.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/git-clone' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/git-clone.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/git-commit' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/git-commit.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/insert-js-after' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/insert-js-after.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/insert-js-before' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/insert-js-before.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/move-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/move-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/parse-js' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/parse-js.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/read-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/read-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/remove-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/remove-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/remove-js-imports' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/remove-js-imports.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/replace-js' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/replace-js.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/visit-js-import' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/visit-js-import.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-ignore-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-ignore-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-js-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-js-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-js-files' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-js-files.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-json-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-json-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-text-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/with-text-file.test' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/write-file' {
  declare module.exports: any;
}

declare module '@dubstep/core/src/utils/write-file.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dubstep/core/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'@dubstep/core/coverage/lcov-report/block-navigation'>;
}
declare module '@dubstep/core/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'@dubstep/core/coverage/lcov-report/prettify'>;
}
declare module '@dubstep/core/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'@dubstep/core/coverage/lcov-report/sorter'>;
}
declare module '@dubstep/core/dist/core/index.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/core/index'>;
}
declare module '@dubstep/core/dist/core/index.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/core/index.test'>;
}
declare module '@dubstep/core/dist/utils/create-restore-point.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/create-restore-point'>;
}
declare module '@dubstep/core/dist/utils/create-restore-point.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/create-restore-point.test'>;
}
declare module '@dubstep/core/dist/utils/ensure-js-imports.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/ensure-js-imports'>;
}
declare module '@dubstep/core/dist/utils/ensure-js-imports.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/ensure-js-imports.test'>;
}
declare module '@dubstep/core/dist/utils/exec.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/exec'>;
}
declare module '@dubstep/core/dist/utils/exec.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/exec.test'>;
}
declare module '@dubstep/core/dist/utils/find-files.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/find-files'>;
}
declare module '@dubstep/core/dist/utils/find-files.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/find-files.test'>;
}
declare module '@dubstep/core/dist/utils/generate-js.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/generate-js'>;
}
declare module '@dubstep/core/dist/utils/generate-js.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/generate-js.test'>;
}
declare module '@dubstep/core/dist/utils/get-restore-point.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/get-restore-point'>;
}
declare module '@dubstep/core/dist/utils/get-restore-point.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/get-restore-point.test'>;
}
declare module '@dubstep/core/dist/utils/git-clone.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/git-clone'>;
}
declare module '@dubstep/core/dist/utils/git-clone.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/git-clone.test'>;
}
declare module '@dubstep/core/dist/utils/git-commit.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/git-commit'>;
}
declare module '@dubstep/core/dist/utils/git-commit.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/git-commit.test'>;
}
declare module '@dubstep/core/dist/utils/insert-js-after.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/insert-js-after'>;
}
declare module '@dubstep/core/dist/utils/insert-js-after.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/insert-js-after.test'>;
}
declare module '@dubstep/core/dist/utils/insert-js-before.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/insert-js-before'>;
}
declare module '@dubstep/core/dist/utils/insert-js-before.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/insert-js-before.test'>;
}
declare module '@dubstep/core/dist/utils/move-file.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/move-file'>;
}
declare module '@dubstep/core/dist/utils/move-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/move-file.test'>;
}
declare module '@dubstep/core/dist/utils/parse-js.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/parse-js'>;
}
declare module '@dubstep/core/dist/utils/parse-js.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/parse-js.test'>;
}
declare module '@dubstep/core/dist/utils/read-file.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/read-file'>;
}
declare module '@dubstep/core/dist/utils/read-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/read-file.test'>;
}
declare module '@dubstep/core/dist/utils/remove-file.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/remove-file'>;
}
declare module '@dubstep/core/dist/utils/remove-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/remove-file.test'>;
}
declare module '@dubstep/core/dist/utils/remove-js-imports.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/remove-js-imports'>;
}
declare module '@dubstep/core/dist/utils/remove-js-imports.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/remove-js-imports.test'>;
}
declare module '@dubstep/core/dist/utils/replace-js.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/replace-js'>;
}
declare module '@dubstep/core/dist/utils/replace-js.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/replace-js.test'>;
}
declare module '@dubstep/core/dist/utils/visit-js-import.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/visit-js-import'>;
}
declare module '@dubstep/core/dist/utils/visit-js-import.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/visit-js-import.test'>;
}
declare module '@dubstep/core/dist/utils/with-ignore-file.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-ignore-file'>;
}
declare module '@dubstep/core/dist/utils/with-ignore-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-ignore-file.test'>;
}
declare module '@dubstep/core/dist/utils/with-js-file.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-js-file'>;
}
declare module '@dubstep/core/dist/utils/with-js-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-js-file.test'>;
}
declare module '@dubstep/core/dist/utils/with-js-files.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-js-files'>;
}
declare module '@dubstep/core/dist/utils/with-js-files.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-js-files.test'>;
}
declare module '@dubstep/core/dist/utils/with-json-file.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-json-file'>;
}
declare module '@dubstep/core/dist/utils/with-json-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-json-file.test'>;
}
declare module '@dubstep/core/dist/utils/with-text-file.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-text-file'>;
}
declare module '@dubstep/core/dist/utils/with-text-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/with-text-file.test'>;
}
declare module '@dubstep/core/dist/utils/write-file.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/write-file'>;
}
declare module '@dubstep/core/dist/utils/write-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/dist/utils/write-file.test'>;
}
declare module '@dubstep/core/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/@babel/cli_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/@babel/parser_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/@babel/parser_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/@babel/plugin-proposal-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/@babel/plugin-proposal-object-rest-spread_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/@babel/plugin-transform-modules-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/@babel/plugin-transform-modules-commonjs_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/@babel/preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/@babel/preset-flow_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/@babel/template_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/@babel/template_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/@babel/traverse_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/@babel/traverse_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/eslint-config-fusion_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/eslint-config-fusion_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/eslint-plugin-cup_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/eslint-plugin-cup_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/eslint-plugin-jest_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/eslint-plugin-jest_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/execa_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/execa_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/flow-coverage-report_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/flow-coverage-report_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/fs-extra_v7.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/fs-extra_v7.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/globby_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/globby_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/ini_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/ini_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/isomorphic-git_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/isomorphic-git_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/jest_v23.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/jest_v23.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/markdown-it_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/markdown-it_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/npm-watch_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/npm-watch_vx.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/prettier_v1.x.x'>;
}
declare module '@dubstep/core/flow-typed/npm/recast_vx.x.x.js' {
  declare module.exports: $Exports<'@dubstep/core/flow-typed/npm/recast_vx.x.x'>;
}
declare module '@dubstep/core/src/core/index.js' {
  declare module.exports: $Exports<'@dubstep/core/src/core/index'>;
}
declare module '@dubstep/core/src/core/index.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/core/index.test'>;
}
declare module '@dubstep/core/src/utils/create-restore-point.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/create-restore-point'>;
}
declare module '@dubstep/core/src/utils/create-restore-point.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/create-restore-point.test'>;
}
declare module '@dubstep/core/src/utils/ensure-js-imports.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/ensure-js-imports'>;
}
declare module '@dubstep/core/src/utils/ensure-js-imports.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/ensure-js-imports.test'>;
}
declare module '@dubstep/core/src/utils/exec.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/exec'>;
}
declare module '@dubstep/core/src/utils/exec.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/exec.test'>;
}
declare module '@dubstep/core/src/utils/find-files.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/find-files'>;
}
declare module '@dubstep/core/src/utils/find-files.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/find-files.test'>;
}
declare module '@dubstep/core/src/utils/generate-js.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/generate-js'>;
}
declare module '@dubstep/core/src/utils/generate-js.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/generate-js.test'>;
}
declare module '@dubstep/core/src/utils/get-restore-point.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/get-restore-point'>;
}
declare module '@dubstep/core/src/utils/get-restore-point.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/get-restore-point.test'>;
}
declare module '@dubstep/core/src/utils/git-clone.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/git-clone'>;
}
declare module '@dubstep/core/src/utils/git-clone.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/git-clone.test'>;
}
declare module '@dubstep/core/src/utils/git-commit.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/git-commit'>;
}
declare module '@dubstep/core/src/utils/git-commit.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/git-commit.test'>;
}
declare module '@dubstep/core/src/utils/insert-js-after.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/insert-js-after'>;
}
declare module '@dubstep/core/src/utils/insert-js-after.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/insert-js-after.test'>;
}
declare module '@dubstep/core/src/utils/insert-js-before.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/insert-js-before'>;
}
declare module '@dubstep/core/src/utils/insert-js-before.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/insert-js-before.test'>;
}
declare module '@dubstep/core/src/utils/move-file.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/move-file'>;
}
declare module '@dubstep/core/src/utils/move-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/move-file.test'>;
}
declare module '@dubstep/core/src/utils/parse-js.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/parse-js'>;
}
declare module '@dubstep/core/src/utils/parse-js.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/parse-js.test'>;
}
declare module '@dubstep/core/src/utils/read-file.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/read-file'>;
}
declare module '@dubstep/core/src/utils/read-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/read-file.test'>;
}
declare module '@dubstep/core/src/utils/remove-file.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/remove-file'>;
}
declare module '@dubstep/core/src/utils/remove-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/remove-file.test'>;
}
declare module '@dubstep/core/src/utils/remove-js-imports.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/remove-js-imports'>;
}
declare module '@dubstep/core/src/utils/remove-js-imports.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/remove-js-imports.test'>;
}
declare module '@dubstep/core/src/utils/replace-js.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/replace-js'>;
}
declare module '@dubstep/core/src/utils/replace-js.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/replace-js.test'>;
}
declare module '@dubstep/core/src/utils/visit-js-import.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/visit-js-import'>;
}
declare module '@dubstep/core/src/utils/visit-js-import.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/visit-js-import.test'>;
}
declare module '@dubstep/core/src/utils/with-ignore-file.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-ignore-file'>;
}
declare module '@dubstep/core/src/utils/with-ignore-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-ignore-file.test'>;
}
declare module '@dubstep/core/src/utils/with-js-file.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-js-file'>;
}
declare module '@dubstep/core/src/utils/with-js-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-js-file.test'>;
}
declare module '@dubstep/core/src/utils/with-js-files.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-js-files'>;
}
declare module '@dubstep/core/src/utils/with-js-files.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-js-files.test'>;
}
declare module '@dubstep/core/src/utils/with-json-file.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-json-file'>;
}
declare module '@dubstep/core/src/utils/with-json-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-json-file.test'>;
}
declare module '@dubstep/core/src/utils/with-text-file.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-text-file'>;
}
declare module '@dubstep/core/src/utils/with-text-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/with-text-file.test'>;
}
declare module '@dubstep/core/src/utils/write-file.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/write-file'>;
}
declare module '@dubstep/core/src/utils/write-file.test.js' {
  declare module.exports: $Exports<'@dubstep/core/src/utils/write-file.test'>;
}
