steps:
  - name: ':docker: build'
    plugins:
      'docker-compose#v1.7.0':
        build: eslint-config-fusion
        image-repository: 296822479253.dkr.ecr.us-east-2.amazonaws.com/fusionjs
  - wait
  - command: yarn flow
    name: ':flowtype:'
    plugins:
      'docker-compose#v1.7.0':
        run: eslint-config-fusion
  - name: ':eslint:'
    command: npm run lint
    plugins:
      'docker-compose#v1.7.0':
        run: eslint-config-fusion
