// flow-typed signature: 0cbfea1751a5d6179792f8874956d1d0
// flow-typed version: <<STUB>>/jest-environment-jsdom_v^24.7.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-jsdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-environment-jsdom/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-environment-jsdom/build/index.js' {
  declare module.exports: $Exports<'jest-environment-jsdom/build/index'>;
}
