dist: trusty
sudo: false
language: node_js
node_js: 8.9.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
before_deploy:
- yarn global add npm-publish-prerelease
- echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
deploy:
  provider: script
  script: npm-publish-prerelease
  on:
    tags: true
env:
  global:
    secure: gTBBIZRc502K1datW9LNQIHO/eIUk20ggrD6iEGHPKsW+/fdS8ghY4bD2AkZJjUsHSsGTGZ392LfVtkW4XXeDHgI0g4Zd/h79Bu1usu1Xyedwww23GMt3kfX+iVujTOa3wXrpuC9pcnB84bujN2BOCzoHzLLe7S7IVbaEF4h6Ze9u0oem3bYq2NpgXbK5euDLez+rdCUnfI1gpxdMY+z2RVEjS3/dFmZom+xVgX5qQtdktQNEsRu+ZRR2Bqgjs6nf5DsIjTg/iNoUCp3OEVXzq8v7a6ySseZl5BrhHoFkvAHmbSrWPS7K7jmuen7lDokAl9edAOVLGFrqLpMkw0O/GWxQ/NSog3UpKoXNnDPZ0K4l9m6NJ9QQ0p91hPIu6C8Qgj13AGx79D0KQ6j/cP+wOD9E7EGPX1ZS5vThmGkCN1468dCe8+0sMyPWoWkKqfSvibECNSCiQKg48eDl9V6ugumB/6MGeGMpHM131iQP4tkwhn85edWl9zgmEKgoguGcXDsSkf/4YpIJNGtWkk5n/O39xc+Iw64tLJwGTu+wOakCOcS0tPRdc3DH7ag7bEgRC/rm8J74knGZ8t4X0odQMGvaUYTKBzVzvPQWdoZyCqUxw+Ke9DFZ8LZozuFz33BCCPzxJHTHxVCf/CHU7qGVIU64PgjtrRr0h6h/D3RVvA=
