// flow-typed signature: 9b6d7ec4e025a9afe905a6f568698545
// flow-typed version: <<STUB>>/@uber/atreyu_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/atreyu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/atreyu' {
  declare module.exports: any;
}
