// flow-typed signature: d57e8a6bb6de3aff07c0bf9dfcb5e1ea
// flow-typed version: <<STUB>>/@uber/awd-client_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/awd-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/awd-client' {
  declare module.exports: any;
}
