// flow-typed signature: 3040e3f811aee91c4aadbb756ade5584
// flow-typed version: <<STUB>>/@uber/bedrock-14-compat_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/bedrock-14-compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/bedrock-14-compat' {
  declare module.exports: any;
}
