// flow-typed signature: a757d4c8c05a0c9b1d9d104a289a99d5
// flow-typed version: <<STUB>>/@uber/flipr-client_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/flipr-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/flipr-client' {
  declare module.exports: any;
}
