// flow-typed signature: f6a4e08738339c643637b014085c7dd5
// flow-typed version: <<STUB>>/@uber/graphql-scripts_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/graphql-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/graphql-scripts' {
  declare module.exports: any;
}
