// flow-typed signature: 71ec4bf52ea39058a313c698ca9300f0
// flow-typed version: <<STUB>>/@uber/icons_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/icons' {
  declare module.exports: any;
}
