// flow-typed signature: 90aa153ddd7bb92b999ae4c03d7608b3
// flow-typed version: <<STUB>>/@uber/jaeger-client_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/jaeger-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/jaeger-client' {
  declare module.exports: any;
}
