// flow-typed signature: 882c6060cf7da5ec44e4c955b7d73d8a
// flow-typed version: <<STUB>>/@uber/m3-client_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/m3-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/m3-client' {
  declare module.exports: any;
}
