// flow-typed signature: f88e7620b5be971311d4c0734867a05a
// flow-typed version: <<STUB>>/@uber/request-m3-events_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/request-m3-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/request-m3-events' {
  declare module.exports: any;
}
