// flow-typed signature: f44bebb501223b00eba6f0d9880e1dc8
// flow-typed version: <<STUB>>/@uber/typed-rpc-cli_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/typed-rpc-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/typed-rpc-cli' {
  declare module.exports: any;
}
