// flow-typed signature: cc1bd00d1f5c95cf46aeda280e8f0977
// flow-typed version: <<STUB>>/@uber/unpm-galileo_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/unpm-galileo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/unpm-galileo' {
  declare module.exports: any;
}
