// flow-typed signature: d8ae0ef91aff79cb9f517aa8d6b312d0
// flow-typed version: <<STUB>>/@uber-web-ui/baseui-codemods_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber-web-ui/baseui-codemods'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber-web-ui/baseui-codemods' {
  declare module.exports: any;
}
