// flow-typed signature: f5e44e38c2c80ae7ceb4ca07f287bea1
// flow-typed version: <<STUB>>/@iarna/toml_v2.2.5/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@iarna/toml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@iarna/toml' {
  declare module.exports: any;
}
