# ═════ Packages to publish ═════

["@uber/create-uber-web"]
# prior : "5.3.4"
version = "5.3.5"

["@uber/fusion-analyticsjs-utils"]
# prior : "2.1.5"
version = "2.1.6"

["@uber/fusion-dev-cli"]
# prior : "3.1.6"
version = "3.1.7"

["@uber/fusion-legacy-styling-compat-mixin"]
# prior : "2.1.5"
version = "2.1.6"

["@uber/fusion-metrics"]
# prior : "1.1.6"
version = "1.1.7"

["@uber/fusion-migrate"]
# prior : "1.3.5"
version = "1.3.6"

["@uber/fusion-plugin-analytics-session"]
# prior : "2.1.6"
version = "2.1.7"

["@uber/fusion-plugin-atreyu"]
# prior : "2.1.8"
version = "2.1.9"

["@uber/fusion-plugin-auth-headers"]
# prior : "4.0.4"
version = "4.0.5"

["@uber/fusion-plugin-bedrock-compat"]
# prior : "2.1.8"
version = "2.1.9"

["@uber/fusion-plugin-error-handling"]
# prior : "2.3.6"
version = "2.3.7"

["@uber/fusion-plugin-events-adapter"]
# prior : "3.3.5"
version = "3.3.6"

["@uber/fusion-plugin-feature-toggles"]
# prior : "3.1.10"
version = "3.1.11"

["@uber/fusion-plugin-feature-toggles-react"]
# prior : "3.1.10"
version = "3.1.11"

["@uber/fusion-plugin-flipr"]
# prior : "2.2.5"
version = "2.2.6"

["@uber/fusion-plugin-galileo"]
# prior : "2.1.8"
version = "2.1.9"

["@uber/fusion-plugin-google-analytics"]
# prior : "2.1.7"
version = "2.1.8"

["@uber/fusion-plugin-graphql-logging-middleware"]
# prior : "1.2.1"
version = "1.2.2"

["@uber/fusion-plugin-graphql-metrics"]
# prior : "1.2.9"
version = "1.2.10"

["@uber/fusion-plugin-heatpipe"]
# prior : "3.1.9"
version = "3.1.10"

["@uber/fusion-plugin-initial-state-compat"]
# prior : "1.1.6"
version = "1.1.7"

["@uber/fusion-plugin-logger"]
# prior : "0.3.1"
version = "0.3.2"

["@uber/fusion-plugin-logtron"]
# prior : "3.3.1"
version = "3.3.2"

["@uber/fusion-plugin-m3"]
# prior : "2.2.1"
version = "2.2.2"

["@uber/fusion-plugin-magellan"]
# prior : "2.1.6"
version = "2.1.7"

["@uber/fusion-plugin-marketing"]
# prior : "2.2.8"
version = "2.2.9"

["@uber/fusion-plugin-page-skeleton-compat"]
# prior : "1.1.6"
version = "1.1.7"

["@uber/fusion-plugin-proxy-compat"]
# prior : "1.1.9"
version = "1.1.10"

["@uber/fusion-plugin-rosetta"]
# prior : "3.0.5"
version = "3.0.6"

["@uber/fusion-plugin-s3-asset-proxying"]
# prior : "2.2.6"
version = "2.2.7"

["@uber/fusion-plugin-secrets"]
# prior : "2.1.6"
version = "2.1.7"

["@uber/fusion-plugin-secure-headers"]
# prior : "5.1.6"
version = "5.1.7"

["@uber/fusion-plugin-tchannel"]
# prior : "2.1.8"
version = "2.1.9"

["@uber/fusion-plugin-tealium"]
# prior : "2.1.7"
version = "2.1.8"

["@uber/fusion-plugin-tracer"]
# prior : "2.1.6"
version = "2.1.7"

["@uber/fusion-plugin-uber-xhr-compat"]
# prior : "1.1.6"
version = "1.1.7"

["@uber/fusion-plugin-universal-logger-compat"]
# prior : "1.1.6"
version = "1.1.7"

["@uber/fusion-plugin-universal-m3-compat"]
# prior : "1.2.1"
version = "1.2.2"

["@uber/fusion-plugin-web-rpc-compat"]
# prior : "1.1.8"
version = "1.1.9"

[eslint-config-fusion]
# prior : "6.2.2"
version = "6.2.3"

[fusion-cli]
# prior : "2.16.1"
version = "2.16.2"

[fusion-core]
# prior : "2.2.5"
version = "2.2.6"

[fusion-plugin-apollo]
# prior : "3.4.8"
version = "3.4.9"

[fusion-plugin-browser-performance-emitter]
# prior : "2.2.8"
version = "2.2.9"

[fusion-plugin-connected-react-router]
# prior : "2.1.11"
version = "2.1.12"

[fusion-plugin-csrf-protection]
# prior : "3.1.7"
version = "3.1.8"

[fusion-plugin-error-handling]
# prior : "2.2.6"
version = "2.2.7"

[fusion-plugin-font-loader-react]
# prior : "2.1.8"
version = "2.1.9"

[fusion-plugin-http-handler]
# prior : "1.1.6"
version = "1.1.7"

[fusion-plugin-i18n]
# prior : "2.4.8"
version = "2.4.9"

[fusion-plugin-i18n-react]
# prior : "3.1.9"
version = "3.1.10"

[fusion-plugin-introspect]
# prior : "1.1.6"
version = "1.1.7"

[fusion-plugin-jwt]
# prior : "2.1.6"
version = "2.1.7"

[fusion-plugin-node-performance-emitter]
# prior : "2.1.8"
version = "2.1.9"

[fusion-plugin-react-helmet-async]
# prior : "2.2.7"
version = "2.2.8"

[fusion-plugin-react-redux]
# prior : "2.2.3"
version = "2.2.4"

[fusion-plugin-react-router]
# prior : "2.2.11"
version = "2.2.12"

[fusion-plugin-redux-action-emitter-enhancer]
# prior : "3.1.8"
version = "3.1.9"

[fusion-plugin-rpc]
# prior : "3.7.0"
version = "3.7.1"

[fusion-plugin-rpc-redux-react]
# prior : "4.3.8"
version = "4.3.9"

[fusion-plugin-service-worker]
# prior : "3.1.12"
version = "3.1.13"

[fusion-plugin-styletron-react]
# prior : "3.2.4"
version = "3.2.5"

[fusion-plugin-universal-events]
# prior : "2.1.8"
version = "2.1.9"

[fusion-plugin-universal-logger]
# prior : "2.1.6"
version = "2.1.7"

[fusion-plugin-web-app-manifest]
# prior : "1.1.6"
version = "1.1.7"

[fusion-react]
# prior : "4.0.7"
version = "4.0.8"

[fusion-rpc-redux]
# prior : "2.2.4"
version = "2.2.5"

[fusion-scaffolder]
# prior : "1.1.4"
version = "1.1.5"

[fusion-test-utils]
# prior : "2.1.6"
version = "2.1.7"

[fusion-tokens]
# prior : "2.1.6"
version = "2.1.7"
