// flow-typed signature: 7952417adf9eaf0eeb9d49e55d1c0471
// flow-typed version: <<STUB>>/@uber/fusion-dev-cli_v^2.0.5/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/fusion-dev-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/fusion-dev-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@uber/fusion-dev-cli/bin/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module '@uber/fusion-dev-cli/bin/cli.js' {
  declare module.exports: $Exports<'@uber/fusion-dev-cli/bin/cli'>;
}
