version: '2'
services:
  fusion-test-utils:
    build: .
    volumes:
      - .:/fusion-test-utils
      - /fusion-test-utils/node_modules/
      - /fusion-test-utils/dist/
      - /fusion-test-utils/dist-tests/
