# ═════ Packages to publish ═════

["@uber/create-uber-web"]
# prior : "2.0.14"
version = "3.0.0"

["@uber/fusion-analyticsjs-utils"]
# prior : "1.0.2"
version = "2.0.0"

["@uber/fusion-dev-cli"]
# prior : "1.1.0"
version = "2.0.0"

["@uber/fusion-legacy-styling-compat-mixin"]
# prior : "1.0.2"
version = "2.0.0"

["@uber/fusion-metrics"]
# prior : "0.0.8"
version = "1.0.0"

["@uber/fusion-migrate"]
# prior : "0.3.23"
version = "1.0.0"

["@uber/fusion-plugin-analytics-session"]
# prior : "1.4.1"
version = "2.0.0"

["@uber/fusion-plugin-atreyu"]
# prior : "1.4.1"
version = "2.0.0"

["@uber/fusion-plugin-auth-headers"]
# prior : "2.0.0"
version = "3.0.0"

["@uber/fusion-plugin-bedrock-compat"]
# prior : "1.0.0"
version = "2.0.0"

["@uber/fusion-plugin-error-handling"]
# prior : "1.0.7"
version = "2.0.0"

["@uber/fusion-plugin-events-adapter"]
# prior : "1.13.1"
version = "2.0.0"

["@uber/fusion-plugin-feature-toggles"]
# prior : "1.0.0"
version = "2.0.0"

["@uber/fusion-plugin-feature-toggles-react"]
# prior : "1.0.0"
version = "2.0.0"

["@uber/fusion-plugin-flipr"]
# prior : "1.0.13"
version = "2.0.0"

["@uber/fusion-plugin-galileo"]
# prior : "1.0.6"
version = "2.0.0"

["@uber/fusion-plugin-google-analytics"]
# prior : "1.0.5"
version = "2.0.0"

["@uber/fusion-plugin-google-analytics-react"]
# prior : "1.0.3"
version = "2.0.0"

["@uber/fusion-plugin-heatpipe"]
# prior : "2.0.0"
version = "3.0.0"

["@uber/fusion-plugin-heatpipe-performance-logger"]
# prior : "0.3.0"
version = "1.0.0"

["@uber/fusion-plugin-initial-state-compat"]
# prior : "0.1.2"
version = "1.0.0"

["@uber/fusion-plugin-logtron"]
# prior : "1.5.0"
version = "2.0.0"

["@uber/fusion-plugin-logtron-react"]
# prior : "1.1.8"
version = "2.0.0"

["@uber/fusion-plugin-m3"]
# prior : "1.3.3"
version = "2.0.0"

["@uber/fusion-plugin-m3-react"]
# prior : "1.1.3"
version = "2.0.0"

["@uber/fusion-plugin-magellan"]
# prior : "1.2.3"
version = "2.0.0"

["@uber/fusion-plugin-marketing"]
# prior : "1.2.2"
version = "2.0.0"

["@uber/fusion-plugin-page-skeleton-compat"]
# prior : "0.1.3"
version = "1.0.0"

["@uber/fusion-plugin-proxy-compat"]
# prior : "0.3.2"
version = "1.0.0"

["@uber/fusion-plugin-react-router-v3-compat"]
# prior : "1.1.2"
version = "2.0.0"

["@uber/fusion-plugin-rosetta"]
# prior : "1.1.4"
version = "2.0.0"

["@uber/fusion-plugin-s3-asset-proxying"]
# prior : "1.2.5"
version = "2.0.0"

["@uber/fusion-plugin-secrets"]
# prior : "1.1.0"
version = "2.0.0"

["@uber/fusion-plugin-secure-headers"]
# prior : "3.2.2"
version = "4.0.0"

["@uber/fusion-plugin-tchannel"]
# prior : "1.1.2"
version = "2.0.0"

["@uber/fusion-plugin-tealium"]
# prior : "1.1.2"
version = "2.0.0"

["@uber/fusion-plugin-tealium-react"]
# prior : "1.0.2"
version = "2.0.0"

["@uber/fusion-plugin-tracer"]
# prior : "1.0.6"
version = "2.0.0"

["@uber/fusion-plugin-uber-xhr-compat"]
# prior : "0.0.3"
version = "1.0.0"

["@uber/fusion-plugin-universal-logger-compat"]
# prior : "0.1.1"
version = "1.0.0"

["@uber/fusion-plugin-universal-m3-compat"]
# prior : "0.1.1"
version = "1.0.0"

["@uber/fusion-plugin-web-rpc-compat"]
# prior : "0.0.1"
version = "1.0.0"

[create-fusion-app]
# prior : "0.1.0"
version = "1.0.0"

[create-fusion-plugin]
# prior : "0.0.4"
version = "1.0.0"

[eslint-config-fusion]
# prior : "5.0.0"
version = "6.0.0"

[fusion-cli]
# prior : "1.18.3"
version = "2.0.0"

[fusion-core]
# prior : "1.10.6"
version = "2.0.0"

[fusion-plugin-apollo]
# prior : "2.0.0-0"
version = "2.0.0"

[fusion-plugin-browser-performance-emitter]
# prior : "1.8.1"
version = "2.0.0"

[fusion-plugin-connected-react-router]
# prior : "1.1.1"
version = "2.0.0"

[fusion-plugin-csrf-protection]
# prior : "2.0.1"
version = "3.0.0"

[fusion-plugin-error-handling]
# prior : "1.1.0"
version = "2.0.0"

[fusion-plugin-font-loader-react]
# prior : "1.2.0"
version = "2.0.0"

[fusion-plugin-http-handler]
# prior : "0.2.0"
version = "1.0.0"

[fusion-plugin-i18n]
# prior : "1.2.2"
version = "2.0.0"

[fusion-plugin-i18n-react]
# prior : "1.2.6"
version = "2.0.0"

[fusion-plugin-introspect]
# prior : "0.2.10"
version = "1.0.0"

[fusion-plugin-jwt]
# prior : "1.0.7"
version = "2.0.0"

[fusion-plugin-node-performance-emitter]
# prior : "1.0.9"
version = "2.0.0"

[fusion-plugin-react-helmet-async]
# prior : "1.0.2"
version = "2.0.0"

[fusion-plugin-react-redux]
# prior : "1.1.2"
version = "2.0.0"

[fusion-plugin-react-router]
# prior : "1.5.4"
version = "2.0.0"

[fusion-plugin-redux-action-emitter-enhancer]
# prior : "2.0.1"
version = "3.0.0"

[fusion-plugin-rpc]
# prior : "2.4.1"
version = "3.0.0"

[fusion-plugin-rpc-redux-react]
# prior : "2.1.1"
version = "3.0.0"

[fusion-plugin-service-worker]
# prior : "2.0.0"
version = "3.0.0"

[fusion-plugin-styletron-react]
# prior : "2.6.1"
version = "3.0.0"

[fusion-plugin-universal-events]
# prior : "1.3.4"
version = "2.0.0"

[fusion-plugin-universal-events-react]
# prior : "1.0.10"
version = "2.0.0"

[fusion-plugin-universal-logger]
# prior : "1.1.0"
version = "2.0.0"

[fusion-react]
# prior : "2.0.0"
version = "3.0.0"

[fusion-rpc-redux]
# prior : "1.4.1"
version = "2.0.0"

[fusion-scaffolder]
# prior : "0.0.2"
version = "1.0.0"

[fusion-test-utils]
# prior : "1.4.1"
version = "2.0.0"

[fusion-tokens]
# prior : "1.1.1"
version = "2.0.0"
