// flow-typed signature: 119a961a21e9846fbb8799454ec0c6fe
// flow-typed version: <<STUB>>/@publisher/npm-helpers_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@publisher/npm-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@publisher/npm-helpers' {
  declare module.exports: any;
}
