// flow-typed signature: cad1149e4818f8c5a7f25dc7cc85d9ef
// flow-typed version: <<STUB>>/@publisher/probot-app_v0.3.1/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@publisher/probot-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@publisher/probot-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@publisher/probot-app/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@publisher/probot-app/index' {
  declare module.exports: $Exports<'@publisher/probot-app'>;
}
declare module '@publisher/probot-app/index.js' {
  declare module.exports: $Exports<'@publisher/probot-app'>;
}
declare module '@publisher/probot-app/test/index.test.js' {
  declare module.exports: $Exports<'@publisher/probot-app/test/index.test'>;
}
