// flow-typed signature: 030e6002cf0a451b0fc746473e3bba91
// flow-typed version: <<STUB>>/@ganemone/babel-flow-types_v2.0.7/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ganemone/babel-flow-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ganemone/babel-flow-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@ganemone/babel-flow-types/index' {
  declare module.exports: $Exports<'@ganemone/babel-flow-types'>;
}
declare module '@ganemone/babel-flow-types/index.js' {
  declare module.exports: $Exports<'@ganemone/babel-flow-types'>;
}
