// @flow
// flow-typed signature: b2c57734b767b3ffb3e3efc4716cbba0
// flow-typed version: <<STUB>>/@uber/heatpipe_v1.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/heatpipe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/heatpipe' {
  declare type TopicInfo = {|
    topic: string,
    version: number,
    lossless?: boolean,
  |};
  declare type Response = {|
    code: string,
    msg: string,
  |};

  declare module.exports: (
    appId: string,
    topicInfo: TopicInfo,
    message: {}
  ) => Promise<Response>;
}
