version: '2'
services:
  fusion-plugin-universal-events-react:
    build: .
    volumes:
      - .:/fusion-plugin-universal-events-react
      - /fusion-plugin-universal-events-react/node_modules/
      - /fusion-plugin-universal-events-react/dist/
      - /fusion-plugin-universal-events-react/dist-tests/
