// flow-typed signature: b65b5366273dee3eb9804e74a8ec437a
// flow-typed version: <<STUB>>/@apollo/react-components_v^3.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@apollo/react-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@apollo/react-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@apollo/react-components/lib/index' {
  declare module.exports: any;
}

declare module '@apollo/react-components/lib/Mutation' {
  declare module.exports: any;
}

declare module '@apollo/react-components/lib/Query' {
  declare module.exports: any;
}

declare module '@apollo/react-components/lib/react-components.cjs' {
  declare module.exports: any;
}

declare module '@apollo/react-components/lib/react-components.cjs.min' {
  declare module.exports: any;
}

declare module '@apollo/react-components/lib/react-components.esm' {
  declare module.exports: any;
}

declare module '@apollo/react-components/lib/react-components.umd' {
  declare module.exports: any;
}

declare module '@apollo/react-components/lib/Subscription' {
  declare module.exports: any;
}

declare module '@apollo/react-components/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@apollo/react-components/lib/index.js' {
  declare module.exports: $Exports<'@apollo/react-components/lib/index'>;
}
declare module '@apollo/react-components/lib/Mutation.js' {
  declare module.exports: $Exports<'@apollo/react-components/lib/Mutation'>;
}
declare module '@apollo/react-components/lib/Query.js' {
  declare module.exports: $Exports<'@apollo/react-components/lib/Query'>;
}
declare module '@apollo/react-components/lib/react-components.cjs.js' {
  declare module.exports: $Exports<'@apollo/react-components/lib/react-components.cjs'>;
}
declare module '@apollo/react-components/lib/react-components.cjs.min.js' {
  declare module.exports: $Exports<'@apollo/react-components/lib/react-components.cjs.min'>;
}
declare module '@apollo/react-components/lib/react-components.esm.js' {
  declare module.exports: $Exports<'@apollo/react-components/lib/react-components.esm'>;
}
declare module '@apollo/react-components/lib/react-components.umd.js' {
  declare module.exports: $Exports<'@apollo/react-components/lib/react-components.umd'>;
}
declare module '@apollo/react-components/lib/Subscription.js' {
  declare module.exports: $Exports<'@apollo/react-components/lib/Subscription'>;
}
declare module '@apollo/react-components/lib/types.js' {
  declare module.exports: $Exports<'@apollo/react-components/lib/types'>;
}
