dist: trusty
sudo: false
language: node_js
node_js: 8.8.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
before_deploy:
- yarn global add npm-publish-prerelease
- echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
deploy:
  provider: script
  script: npm-publish-prerelease
  on:
    tags: true
env:
  global:
    secure: U6xyVB8k06OoL3aSJmQzZP9OnpBJK+t6W4+Sf22MfwRjXzMWCFmVsb+S7usUaNkXEFOiYlDTV3DeJYe5Q6adjsXfHypP2anfRtJfEJMefG3fpg528Ca/ozXhD00pSp8SwmmdWMka1m9f+wteEl8dhZ4FTlgGACdJFsKRFNa1Qo4548yzxSKtWz4u2qdUe3yh28vyVlEYDtT3U5wCwA5sJeOiEkMHJ8FQckNo0fzcnzqWlHd+brzgXeAuMnY/5hRL8fyzPO72sId1XwIrUMF0FkhctiyjlWxi3tXsJM3c92ejDXZWTNnXEz5SYZ8jrsD8ESOmpPs5DB3jUev78uhCnFwe/mWxvZ/x8hidfZm1PGGZTdQI4pc+fyeZZBAiy1SQlrYif1anho2jz014Pc5vwFUGtdk4J1GH8Uu+y+PffqxrOQyfp8QiyTPPb5bdMvVOpJRLuNAYnOWB766xSXesII8IqxMIlHrUZbUYZQdVOS+wxwQp32OtPX4PqAbFrX1ib4SjZsacqUU6qOe7EAq0B+VSItVwSVzEWiT/6farPhSB28jX5Exh2FcuJ6tLub7NElU6oHg8fMJVDLY2A21WfwUQZf14dnNrW1oh4qb3/87pDHjF6nBAkKy0XGUtxXWFAVhDZK2QQP2+oAFfWp5jz+XWjxAjedsEMWv0GgOCj2E=
