// flow-typed signature: 8615971bf56dea74cee3836e133e434f
// flow-typed version: <<STUB>>/@uber/typed-rpc-cli_v^2.3.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uber/typed-rpc-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uber/typed-rpc-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@uber/typed-rpc-cli/bin/cli' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/config.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/convert-case.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/flow-from-schema' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/graphql-link' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/merge-configs' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/multiple-service-graphql' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/multiple-service-web-rpc' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/replace-extension.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/single-service-graphql' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/single-service-web-rpc' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/staging-graphql' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/__tests__/update-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/add-comment' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/babel-opts' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/babel-plugin-transform-tree-shake' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/convert-case' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/ensure-import-declaration' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/file-utils' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-graphql-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-plugin-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-plugin-register-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-register-graphql-links' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-register-graphql-plugins' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-resolvers' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-rpc-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-schemas' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate-type-imports' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/generate' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-atreyu-config-path' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-flow-files' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-json-descriptor-files' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-named-exports' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-rpc-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-services' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-thrift-files' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/get-unique-token-plugin-pair' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/graphql-to-flow/index' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/graphql-to-flow/index.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/index' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/link' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/load-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/main' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/mod-flow' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/codegen-link-plugins' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/codegen-plugins' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/generate-graphql-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/generate-register-graphql-links' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/generate-resolvers' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/generate-rpc-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/generate-schemas' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/generate' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/get-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/get-filtered-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/get-paths' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/get-rpc-code' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/idl' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/index' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/install-plugins' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/link' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/lint-projects' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/merge-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/babel.config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/enzyme.config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/globals' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/npm/enzyme-adapter-react-16_vx.x.x' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/npm/jest_v23.x.x' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/src/test-utils/graphql-test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/register-plugins' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/scaffold-plugin' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/update-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/monorepo/update-link-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/parse-config' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/proto-to-flow/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/proto-to-flow/index' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/remove-unused-imports' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/replace-extension' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/test-utils/run-test' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/to-cjs' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/update-flow' {
  declare module.exports: any;
}

declare module '@uber/typed-rpc-cli/src/update-main-schema' {
  declare module.exports: any;
}

// Filename aliases
declare module '@uber/typed-rpc-cli/bin/cli.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/bin/cli'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/config.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/config.test'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/convert-case.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/convert-case.test'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/flow-from-schema.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/flow-from-schema'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/graphql-link.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/graphql-link'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/merge-configs.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/merge-configs'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/multiple-service-graphql.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/multiple-service-graphql'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/multiple-service-web-rpc.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/multiple-service-web-rpc'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/replace-extension.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/replace-extension.test'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/single-service-graphql.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/single-service-graphql'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/single-service-web-rpc.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/single-service-web-rpc'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/staging-graphql.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/staging-graphql'>;
}
declare module '@uber/typed-rpc-cli/src/__tests__/update-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/__tests__/update-config'>;
}
declare module '@uber/typed-rpc-cli/src/add-comment.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/add-comment'>;
}
declare module '@uber/typed-rpc-cli/src/babel-opts.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/babel-opts'>;
}
declare module '@uber/typed-rpc-cli/src/babel-plugin-transform-tree-shake.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/babel-plugin-transform-tree-shake'>;
}
declare module '@uber/typed-rpc-cli/src/convert-case.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/convert-case'>;
}
declare module '@uber/typed-rpc-cli/src/ensure-import-declaration.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/ensure-import-declaration'>;
}
declare module '@uber/typed-rpc-cli/src/file-utils.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/file-utils'>;
}
declare module '@uber/typed-rpc-cli/src/generate-graphql-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-graphql-code'>;
}
declare module '@uber/typed-rpc-cli/src/generate-plugin-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-plugin-code'>;
}
declare module '@uber/typed-rpc-cli/src/generate-plugin-register-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-plugin-register-code'>;
}
declare module '@uber/typed-rpc-cli/src/generate-register-graphql-links.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-register-graphql-links'>;
}
declare module '@uber/typed-rpc-cli/src/generate-register-graphql-plugins.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-register-graphql-plugins'>;
}
declare module '@uber/typed-rpc-cli/src/generate-resolvers.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-resolvers'>;
}
declare module '@uber/typed-rpc-cli/src/generate-rpc-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-rpc-code'>;
}
declare module '@uber/typed-rpc-cli/src/generate-schemas.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-schemas'>;
}
declare module '@uber/typed-rpc-cli/src/generate-type-imports.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate-type-imports'>;
}
declare module '@uber/typed-rpc-cli/src/generate.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/generate'>;
}
declare module '@uber/typed-rpc-cli/src/get-atreyu-config-path.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-atreyu-config-path'>;
}
declare module '@uber/typed-rpc-cli/src/get-flow-files.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-flow-files'>;
}
declare module '@uber/typed-rpc-cli/src/get-json-descriptor-files.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-json-descriptor-files'>;
}
declare module '@uber/typed-rpc-cli/src/get-named-exports.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-named-exports'>;
}
declare module '@uber/typed-rpc-cli/src/get-rpc-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-rpc-code'>;
}
declare module '@uber/typed-rpc-cli/src/get-services.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-services'>;
}
declare module '@uber/typed-rpc-cli/src/get-thrift-files.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-thrift-files'>;
}
declare module '@uber/typed-rpc-cli/src/get-unique-token-plugin-pair.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/get-unique-token-plugin-pair'>;
}
declare module '@uber/typed-rpc-cli/src/graphql-to-flow/index.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/graphql-to-flow/index'>;
}
declare module '@uber/typed-rpc-cli/src/graphql-to-flow/index.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/graphql-to-flow/index.test'>;
}
declare module '@uber/typed-rpc-cli/src/index.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/index'>;
}
declare module '@uber/typed-rpc-cli/src/link.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/link'>;
}
declare module '@uber/typed-rpc-cli/src/load-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/load-config'>;
}
declare module '@uber/typed-rpc-cli/src/main.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/main'>;
}
declare module '@uber/typed-rpc-cli/src/mod-flow.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/mod-flow'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/codegen-link-plugins.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/codegen-link-plugins'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/codegen-plugins.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/codegen-plugins'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/generate-graphql-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/generate-graphql-code'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/generate-register-graphql-links.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/generate-register-graphql-links'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/generate-resolvers.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/generate-resolvers'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/generate-rpc-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/generate-rpc-code'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/generate-schemas.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/generate-schemas'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/generate.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/generate'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/get-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/get-config'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/get-filtered-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/get-filtered-config'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/get-paths.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/get-paths'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/get-rpc-code.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/get-rpc-code'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/idl.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/idl'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/index.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/index'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/install-plugins.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/install-plugins'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/link.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/link'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/lint-projects.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/lint-projects'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/merge-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/merge-config'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/babel.config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/plugin-template/babel.config'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/enzyme.config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/plugin-template/enzyme.config'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/globals.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/globals'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/npm/enzyme_v3.x.x'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/npm/enzyme-adapter-react-16_vx.x.x.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/npm/enzyme-adapter-react-16_vx.x.x'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/npm/jest_v23.x.x.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/plugin-template/flow-typed/npm/jest_v23.x.x'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/plugin-template/src/test-utils/graphql-test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/plugin-template/src/test-utils/graphql-test'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/register-plugins.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/register-plugins'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/scaffold-plugin.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/scaffold-plugin'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/update-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/update-config'>;
}
declare module '@uber/typed-rpc-cli/src/monorepo/update-link-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/monorepo/update-link-config'>;
}
declare module '@uber/typed-rpc-cli/src/parse-config.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/parse-config'>;
}
declare module '@uber/typed-rpc-cli/src/proto-to-flow/__tests__/index.test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/proto-to-flow/__tests__/index.test'>;
}
declare module '@uber/typed-rpc-cli/src/proto-to-flow/index.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/proto-to-flow/index'>;
}
declare module '@uber/typed-rpc-cli/src/remove-unused-imports.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/remove-unused-imports'>;
}
declare module '@uber/typed-rpc-cli/src/replace-extension.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/replace-extension'>;
}
declare module '@uber/typed-rpc-cli/src/test-utils/run-test.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/test-utils/run-test'>;
}
declare module '@uber/typed-rpc-cli/src/to-cjs.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/to-cjs'>;
}
declare module '@uber/typed-rpc-cli/src/update-flow.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/update-flow'>;
}
declare module '@uber/typed-rpc-cli/src/update-main-schema.js' {
  declare module.exports: $Exports<'@uber/typed-rpc-cli/src/update-main-schema'>;
}
