version: '2'
services:
  fusion-plugin-node-performance-emitter:
    build: .
    volumes:
      - .:/fusion-plugin-node-performance-emitter
      - /fusion-plugin-node-performance-emitter/node_modules/
      - /fusion-plugin-node-performance-emitter/dist/
      - /fusion-plugin-node-performance-emitter/dist-tests/
