// flow-typed signature: 69a1b7e7f16f23d3bb9d5c2d2efb2f85
// flow-typed version: <<STUB>>/@publisher/core/package-hashes.js_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@publisher/core/package-hashes.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@publisher/core/package-hashes.js' {
  declare module.exports: any;
}
