// flow-typed signature: fa24376503823a018e74383ee9ab0ab6
// flow-typed version: <<STUB>>/compression-webpack-plugin_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compression-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compression-webpack-plugin' {
  declare module.exports: any;
}
