// flow-typed signature: eb6ae991f45ca66ef19a4ae9df924828
// flow-typed version: <<STUB>>/baseui/button_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'baseui/button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'baseui/button' {
  declare module.exports: any;
}
