/* eslint-env node */

import path from 'path';
import test from 'tape';
import plugin from '../../server';

test('interface', async t => {
  t.equals(typeof plugin, 'function');

  const config = {
    config: {
      serviceNames: ['safari'],
    },
    options: {
      // the idl folder is generated by the npm test script prior to building the test
      idlFolderPath: path.join(__dirname, 'idl'),
      statsd: {gauge() {}, timing() {}, increment() {}},
    },
    graphs: {
      countryGraph: {
        all: {
          service: 'safari',
          method: 'Safari::searchCountries',
          args: {
            request: {},
          },
        },
      },
    },
  };
  const Atreyu = plugin(config);
  const instance = Atreyu.of();
  t.equals(typeof instance.graphs, 'object');
  t.equals(typeof instance.requests, 'object');

  const countries = await instance.graphs.countryGraph.resolve();
  t.ok(countries.all instanceof Array, 'has response');
  t.ok(countries.all.length > 0, 'has data');
  t.ok(typeof countries.all[0].name === 'string', 'has right data');
  Atreyu.cleanup();
  t.end();
});
