# ═════ Packages to publish ═════

["@uber/create-uber-web"]
# prior : "4.0.0"
version = "4.0.1"

["@uber/fusion-metrics"]
# prior : "1.0.7"
version = "1.0.8"

[fusion-cli]
# prior : "2.4.1"
version = "2.4.2"

[fusion-plugin-introspect]
# prior : "1.0.7"
version = "1.0.8"

[fusion-plugin-service-worker]
# prior : "3.0.20"
version = "3.0.21"

["@uber/fusion-plugin-atreyu"]
# prior = "2.0.8"
version = "2.0.9"

["@uber/fusion-plugin-graphql-logging-middleware"]
# prior = "1.0.5"
version = "1.0.6"

# ═════ Unchanged packages ═════

["@uber/fusion-analyticsjs-utils"]
publish = false
version = "2.0.2"

["@uber/fusion-dev-cli"]
publish = false
version = "2.0.6"

["@uber/fusion-legacy-styling-compat-mixin"]
publish = false
version = "2.0.2"

["@uber/fusion-migrate"]
publish = false
version = "1.2.2"

["@uber/fusion-plugin-analytics-session"]
publish = false
version = "2.0.7"

["@uber/fusion-plugin-auth-headers"]
publish = false
version = "3.0.6"

["@uber/fusion-plugin-bedrock-compat"]
publish = false
version = "2.0.8"

["@uber/fusion-plugin-error-handling"]
publish = false
version = "2.0.8"

["@uber/fusion-plugin-events-adapter"]
publish = false
version = "2.1.5"

["@uber/fusion-plugin-feature-toggles"]
publish = false
version = "3.0.8"

["@uber/fusion-plugin-feature-toggles-react"]
publish = false
version = "3.0.8"

["@uber/fusion-plugin-flipr"]
publish = false
version = "2.0.6"

["@uber/fusion-plugin-galileo"]
publish = false
version = "2.0.8"

["@uber/fusion-plugin-google-analytics"]
publish = false
version = "2.0.7"

["@uber/fusion-plugin-google-analytics-react"]
publish = false
version = "2.0.7"

["@uber/fusion-plugin-graphql-metrics"]
publish = false
version = "1.0.4"

["@uber/fusion-plugin-heatpipe"]
publish = false
version = "3.0.8"

["@uber/fusion-plugin-initial-state-compat"]
publish = false
version = "1.0.6"

["@uber/fusion-plugin-logtron"]
publish = false
version = "2.0.8"

["@uber/fusion-plugin-logtron-react"]
publish = false
version = "2.1.5"

["@uber/fusion-plugin-m3"]
publish = false
version = "2.0.8"

["@uber/fusion-plugin-m3-react"]
publish = false
version = "2.0.8"

["@uber/fusion-plugin-magellan"]
publish = false
version = "2.0.6"

["@uber/fusion-plugin-marketing"]
publish = false
version = "2.0.8"

["@uber/fusion-plugin-page-skeleton-compat"]
publish = false
version = "1.0.7"

["@uber/fusion-plugin-proxy-compat"]
publish = false
version = "1.0.8"

["@uber/fusion-plugin-rosetta"]
publish = false
version = "2.2.0"

["@uber/fusion-plugin-s3-asset-proxying"]
publish = false
version = "2.0.7"

["@uber/fusion-plugin-secrets"]
publish = false
version = "2.0.7"

["@uber/fusion-plugin-secure-headers"]
publish = false
version = "5.0.7"

["@uber/fusion-plugin-tchannel"]
publish = false
version = "2.0.8"

["@uber/fusion-plugin-tealium"]
publish = false
version = "2.0.6"

["@uber/fusion-plugin-tealium-react"]
publish = false
version = "2.0.7"

["@uber/fusion-plugin-tracer"]
publish = false
version = "2.0.6"

["@uber/fusion-plugin-uber-xhr-compat"]
publish = false
version = "1.0.7"

["@uber/fusion-plugin-universal-logger-compat"]
publish = false
version = "1.0.7"

["@uber/fusion-plugin-universal-m3-compat"]
publish = false
version = "1.0.8"

["@uber/fusion-plugin-web-rpc-compat"]
publish = false
version = "1.0.8"

[create-fusion-app]
publish = false
version = "1.0.6"

[create-fusion-plugin]
publish = false
version = "1.0.6"

[eslint-config-fusion]
publish = false
version = "6.0.4"

[fusion-core]
publish = false
version = "2.0.6"

[fusion-plugin-apollo]
publish = false
version = "3.1.0"

[fusion-plugin-browser-performance-emitter]
publish = false
version = "2.1.8"

[fusion-plugin-connected-react-router]
publish = false
version = "2.0.8"

[fusion-plugin-csrf-protection]
publish = false
version = "3.0.6"

[fusion-plugin-error-handling]
publish = false
version = "2.1.4"

[fusion-plugin-font-loader-react]
publish = false
version = "2.0.6"

[fusion-plugin-http-handler]
publish = false
version = "1.0.7"

[fusion-plugin-i18n]
publish = false
version = "2.3.2"

[fusion-plugin-i18n-react]
publish = false
version = "3.0.5"

[fusion-plugin-jwt]
publish = false
version = "2.0.6"

[fusion-plugin-node-performance-emitter]
publish = false
version = "2.0.8"

[fusion-plugin-react-helmet-async]
publish = false
version = "2.1.2"

[fusion-plugin-react-redux]
publish = false
version = "2.0.6"

[fusion-plugin-react-router]
publish = false
version = "2.0.8"

[fusion-plugin-redux-action-emitter-enhancer]
publish = false
version = "3.0.8"

[fusion-plugin-rpc]
publish = false
version = "3.3.0"

[fusion-plugin-rpc-redux-react]
publish = false
version = "4.0.5"

[fusion-plugin-styletron-react]
publish = false
version = "3.0.9"

[fusion-plugin-universal-events]
publish = false
version = "2.0.7"

[fusion-plugin-universal-events-react]
publish = false
version = "2.1.5"

[fusion-plugin-universal-logger]
publish = false
version = "2.0.6"

[fusion-plugin-web-app-manifest]
publish = false
version = "1.0.5"

[fusion-react]
publish = false
version = "3.1.5"

[fusion-rpc-redux]
publish = false
version = "2.0.4"

[fusion-scaffolder]
publish = false
version = "1.0.6"

[fusion-test-utils]
publish = false
version = "2.0.6"

[fusion-tokens]
publish = false
version = "2.0.6"

[jazelle]
publish = false
version = "0.0.0-alpha.3"


